// Generated by tools/phosphor/phosphor_tool.py. Do not edit by hand.
package com.v16studio.v16service.ui.icons

import androidx.annotation.DrawableRes
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.material3.LocalContentColor
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.res.painterResource
import com.v16studio.v16service.R

object V16ServiceIcons {
    @DrawableRes val Add = R.drawable.ic_v16s_add
    @DrawableRes val Appearance = R.drawable.ic_v16s_appearance
    @DrawableRes val ArrowCircleDown = R.drawable.ic_v16s_arrow_circle_down
    @DrawableRes val ArrowCircleUp = R.drawable.ic_v16s_arrow_circle_up
    @DrawableRes val ArrowDown = R.drawable.ic_v16s_arrow_down
    @DrawableRes val ArrowFatLineDown = R.drawable.ic_v16s_arrow_fat_line_down
    @DrawableRes val ArrowFatLineUp = R.drawable.ic_v16s_arrow_fat_line_up
    @DrawableRes val ArrowUp = R.drawable.ic_v16s_arrow_up
    @DrawableRes val ArrowsDownUp = R.drawable.ic_v16s_arrows_down_up
    @DrawableRes val Back = R.drawable.ic_v16s_back
    @DrawableRes val Backup = R.drawable.ic_v16s_backup
    @DrawableRes val Bug = R.drawable.ic_v16s_bug
    @DrawableRes val Calendar = R.drawable.ic_v16s_calendar
    @DrawableRes val Call = R.drawable.ic_v16s_call
    @DrawableRes val Camera = R.drawable.ic_v16s_camera
    @DrawableRes val CaretDown = R.drawable.ic_v16s_caret_down
    @DrawableRes val CaretRight = R.drawable.ic_v16s_caret_right
    @DrawableRes val Check = R.drawable.ic_v16s_check
    @DrawableRes val CheckCircle = R.drawable.ic_v16s_check_circle
    @DrawableRes val CheckFat = R.drawable.ic_v16s_check_fat
    @DrawableRes val Circle = R.drawable.ic_v16s_circle
    @DrawableRes val ContactOtherCamera = R.drawable.ic_v16s_contact_other_camera
    @DrawableRes val ContactOtherWebcam = R.drawable.ic_v16s_contact_other_webcam
    @DrawableRes val Copy = R.drawable.ic_v16s_copy
    @DrawableRes val Customers = R.drawable.ic_v16s_customers
    @DrawableRes val Delete = R.drawable.ic_v16s_delete
    @DrawableRes val Disclosure = R.drawable.ic_v16s_disclosure
    @DrawableRes val Dropdown = R.drawable.ic_v16s_dropdown
    @DrawableRes val Equipment = R.drawable.ic_v16s_equipment
    @DrawableRes val Error = R.drawable.ic_v16s_error
    @DrawableRes val Expand = R.drawable.ic_v16s_expand
    @DrawableRes val ExternalOpen = R.drawable.ic_v16s_external_open
    @DrawableRes val EyeSlash = R.drawable.ic_v16s_eye_slash
    @DrawableRes val History = R.drawable.ic_v16s_history
    @DrawableRes val Home = R.drawable.ic_v16s_home
    @DrawableRes val HomeFollowUp = R.drawable.ic_v16s_home_follow_up
    @DrawableRes val HomeService = R.drawable.ic_v16s_home_service
    @DrawableRes val HomeVisit = R.drawable.ic_v16s_home_visit
    @DrawableRes val Info = R.drawable.ic_v16s_info
    @DrawableRes val InspectionTemplates = R.drawable.ic_v16s_inspection_templates
    @DrawableRes val LocalSaved = R.drawable.ic_v16s_local_saved
    @DrawableRes val Lock = R.drawable.ic_v16s_lock
    @DrawableRes val Mail = R.drawable.ic_v16s_mail
    @DrawableRes val More = R.drawable.ic_v16s_more
    @DrawableRes val PencilSimple = R.drawable.ic_v16s_pencil_simple
    @DrawableRes val Person = R.drawable.ic_v16s_person
    @DrawableRes val Photo = R.drawable.ic_v16s_photo
    @DrawableRes val PlusBold = R.drawable.ic_v16s_plus_bold
    @DrawableRes val Report = R.drawable.ic_v16s_report
    @DrawableRes val Restore = R.drawable.ic_v16s_restore
    @DrawableRes val Search = R.drawable.ic_v16s_search
    @DrawableRes val SelectionCheck = R.drawable.ic_v16s_selection_check
    @DrawableRes val SelectionChecked = R.drawable.ic_v16s_selection_checked
    @DrawableRes val SelectionEmpty = R.drawable.ic_v16s_selection_empty
    @DrawableRes val Settings = R.drawable.ic_v16s_settings
    @DrawableRes val Share = R.drawable.ic_v16s_share
    @DrawableRes val Site = R.drawable.ic_v16s_site
    @DrawableRes val Sms = R.drawable.ic_v16s_sms
    @DrawableRes val TeamRole = R.drawable.ic_v16s_team_role
    @DrawableRes val Time = R.drawable.ic_v16s_time
    @DrawableRes val Warning = R.drawable.ic_v16s_warning
    @DrawableRes val WarningCircle = R.drawable.ic_v16s_warning_circle
    @DrawableRes val Work = R.drawable.ic_v16s_work
    @DrawableRes val X = R.drawable.ic_v16s_x
    @DrawableRes val XCircle = R.drawable.ic_v16s_x_circle
}

@Composable
fun v16ServiceIconPainter(@DrawableRes icon: Int): Painter = painterResource(icon)

@Composable
fun V16ServiceIcon(
    @DrawableRes icon: Int,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    tint: Color = LocalContentColor.current,
) = Icon(v16ServiceIconPainter(icon), contentDescription, modifier, tint)
