package com.v16studio.serviceloop.ui

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Button
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Card
import androidx.compose.material3.Checkbox
import androidx.compose.material3.FilterChip
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.unit.dp
import androidx.core.content.FileProvider
import androidx.navigation.NavHostController
import com.v16studio.serviceloop.ServiceLoopApplication
import com.v16studio.serviceloop.data.DispatchItemBindingEntity
import com.v16studio.serviceloop.data.DispatchPackageCodec
import com.v16studio.serviceloop.data.DispatchPackageService
import com.v16studio.serviceloop.data.DispatchDuplicateDecision
import com.v16studio.serviceloop.data.HandoffReview
import com.v16studio.serviceloop.data.DispatchTechnicianSnapshot
import com.v16studio.serviceloop.data.DispatchVisitBindingEntity
import com.v16studio.serviceloop.data.TECHNICIAN_IDENTITY_MIME
import com.v16studio.serviceloop.data.TechnicianIdentity
import com.v16studio.serviceloop.data.TechnicianIdentityCodec
import com.v16studio.serviceloop.data.WORK_PACKAGE_MIME
import com.v16studio.serviceloop.domain.VisitDetail
import java.io.ByteArrayOutputStream
import java.io.File
import java.time.LocalDate
import java.time.ZoneId
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

internal const val DISPATCH_PREFS = "dispatch_prototype"
internal const val COORDINATOR_ENABLED = "coordinator_enabled"
internal const val OFFICE_EMAIL = "office_email"

internal fun reportShareEligible(filePresent:Boolean,voided:Boolean,renditionKind:String,historical:Boolean,acknowledged:Boolean)=filePresent&&(!voided||renditionKind=="VOID_NOTICE")&&(!historical||voided||acknowledged)
internal fun reportShareIntent(uri:Uri,officeEmail:String?=null)=Intent(Intent.ACTION_SEND).setType("application/pdf").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION).apply{officeEmail?.takeIf{it.isNotBlank()}?.let{putExtra(Intent.EXTRA_EMAIL,arrayOf(it))}}

private fun service(context:Context)=DispatchPackageService((context.applicationContext as ServiceLoopApplication).container.database,context.filesDir)
private fun java.io.InputStream.readBounded(limit:Int):ByteArray{val out=ByteArrayOutputStream();val b=ByteArray(8192);while(true){val n=read(b);if(n<0)break;require(out.size()+n<=limit){"Selected file is too large"};out.write(b,0,n)};return out.toByteArray()}
private fun shareFile(context:Context,dirName:String,fileName:String,mime:String,bytes:ByteArray,title:String){val dir=File(context.cacheDir,dirName).apply{mkdirs();listFiles()?.filter{it.lastModified()<System.currentTimeMillis()-86_400_000}?.forEach(File::delete)};val file=File(dir,fileName).apply{writeBytes(bytes)};val uri=FileProvider.getUriForFile(context,"${context.packageName}.reports",file);context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).setType(mime).putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION),title))}

@Composable internal fun DispatchSettings(padding:PaddingValues,nav:NavHostController){val context=LocalContext.current;val prefs=remember{context.getSharedPreferences(DISPATCH_PREFS,0)};var enabled by rememberSaveable{mutableStateOf(prefs.getBoolean(COORDINATOR_ENABLED,false))};var email by rememberSaveable{mutableStateOf(prefs.getString(OFFICE_EMAIL,"").orEmpty())};LazyColumn(Modifier.padding(padding),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Technician identity",style=MaterialTheme.typography.titleLarge);Text("Every installation has a stable routing identity, separate from report identity.");Button({nav.navigate("dispatch/identity")},Modifier.fillMaxWidth()){Text("Open Technician identity")}};item{Text("Experimental coordinator conveniences",style=MaterialTheme.typography.titleLarge);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text("Coordinator tools");Text("File-based dispatch only. No accounts, synchronization, or shared database.",style=MaterialTheme.typography.bodySmall)};Checkbox(enabled,{enabled=it;prefs.edit().putBoolean(COORDINATOR_ENABLED,it).apply()},Modifier.testTag("coordinator-tools-switch"))}};if(enabled){item{Button({nav.navigate("dispatch/technicians")},Modifier.fillMaxWidth()){Text("Technicians")};Button({nav.navigate("dispatch/teams")},Modifier.fillMaxWidth()){Text("Teams and leaders")};Button({nav.navigate("dispatch/create")},Modifier.fillMaxWidth()){Text("Dispatch outbox")}}};item{OutlinedTextField(email,{email=it;prefs.edit().putString(OFFICE_EMAIL,it.trim()).apply()},label={Text("Office report recipient · Optional")},modifier=Modifier.fillMaxWidth())}}}

@Composable internal fun TechnicianIdentityScreen(padding:PaddingValues){val context=LocalContext.current;val svc=remember{service(context)};val scope=rememberCoroutineScope();var value by remember{mutableStateOf<TechnicianIdentity?>(null)};var name by rememberSaveable{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};LaunchedEffect(Unit){value=withContext(Dispatchers.IO){svc.identity()};name=value!!.name};LazyColumn(Modifier.padding(padding).testTag("technician-identity"),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Technician identity",style=MaterialTheme.typography.headlineSmall);Text("Your Technician ID identifies this ServiceLoop installation in dispatch packages. It is not an account or password.");OutlinedTextField(name,{name=it},label={Text("Name")},modifier=Modifier.fillMaxWidth());Text("Technician ID\n${value?.technicianId.orEmpty()}");Button({scope.launch{runCatching{withContext(Dispatchers.IO){svc.renameIdentity(name)}}.onSuccess{value=it}.onFailure{error=it.message}}},enabled=name.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text("Save name")};OutlinedButton({value?.let{(context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager).setPrimaryClip(ClipData.newPlainText("ServiceLoop Technician ID",it.technicianId))}},Modifier.fillMaxWidth()){Text("Copy ID")};OutlinedButton({value?.let{v->scope.launch{withContext(Dispatchers.IO){TechnicianIdentityCodec.encode(v)}.let{shareFile(context,"technician-identity","serviceloop-${v.technicianId.take(8)}.sltech",TECHNICIAN_IDENTITY_MIME,it,"Share ServiceLoop Technician identity")}}}},Modifier.fillMaxWidth()){Text("Share identity")};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}}}

@Composable internal fun DispatchTechniciansScreen(padding:PaddingValues){
    val context=LocalContext.current;val svc=remember{service(context)};val scope=rememberCoroutineScope()
    var techs by remember{mutableStateOf(emptyList<com.v16studio.serviceloop.data.DispatchTechnicianEntity>())};var id by rememberSaveable{mutableStateOf("")};var name by rememberSaveable{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};var rename by remember{mutableStateOf<com.v16studio.serviceloop.data.TechnicianRenameReview?>(null)}
    fun reload(){scope.launch{techs=withContext(Dispatchers.IO){svc.technicians()}}}
    fun submit(value:TechnicianIdentity){scope.launch{runCatching{withContext(Dispatchers.IO){svc.technicianRenameReview(value)}}.onSuccess{review->if(review!=null)rename=review else scope.launch{withContext(Dispatchers.IO){svc.importTechnician(value)};id="";name="";reload()}}.onFailure{error=it.message}}}
    LaunchedEffect(Unit){reload()}
    val open=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->uri?.let{scope.launch{runCatching{withContext(Dispatchers.IO){val bytes=context.contentResolver.openInputStream(it)!!.use{x->x.readBounded(TechnicianIdentityCodec.MAX_BYTES)};TechnicianIdentityCodec.decode(bytes)}}.onSuccess(::submit).onFailure{if(it is CancellationException)throw it else error=it.message}}}}
    rename?.let{review->AlertDialog(modifier=Modifier.testTag("technician-rename-dialog"),onDismissRequest={rename=null},title={Text("Technician ID already exists")},text={Text("Old name: ${review.existingName}\nIncoming name: ${review.incoming.name}")},dismissButton={TextButton({rename=null},Modifier.testTag("technician-rename-keep")){Text("Keep existing name")}},confirmButton={Button({scope.launch{withContext(Dispatchers.IO){svc.importTechnician(review.incoming,true)};rename=null;id="";name="";reload()}},Modifier.testTag("technician-rename-update")){Text("Update name")}})}
    LazyColumn(Modifier.padding(padding).testTag("dispatch-technicians"),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Technicians",style=MaterialTheme.typography.headlineSmall);Text("Technician IDs route readable unsigned files; they are not authentication.");Button({open.launch(arrayOf(TECHNICIAN_IDENTITY_MIME,"application/json"))},Modifier.fillMaxWidth()){Text("Import .sltech")};OutlinedTextField(id,{id=it},label={Text("Technician ID")},modifier=Modifier.fillMaxWidth());OutlinedTextField(name,{name=it},label={Text("Name")},modifier=Modifier.fillMaxWidth());OutlinedButton({submit(TechnicianIdentity(id.trim(),name.trim()))},enabled=id.isNotBlank()&&name.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text("Add manually")};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}};items(techs){Text("${it.displayName}\n${it.technicianId}")}}
}
@Composable internal fun DispatchTeamsScreen(padding:PaddingValues){val context=LocalContext.current;val svc=remember{service(context)};val scope=rememberCoroutineScope();var teams by remember{mutableStateOf(emptyList<com.v16studio.serviceloop.data.DispatchTeamDetail>())};var techs by remember{mutableStateOf(emptyList<com.v16studio.serviceloop.data.DispatchTechnicianEntity>())};var name by rememberSaveable{mutableStateOf("")};fun reload(){scope.launch{teams=withContext(Dispatchers.IO){svc.teams()};techs=withContext(Dispatchers.IO){svc.technicians()}}};LaunchedEffect(Unit){reload()};LazyColumn(Modifier.padding(padding).testTag("dispatch-teams"),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Teams and leaders",style=MaterialTheme.typography.headlineSmall);OutlinedTextField(name,{name=it},label={Text("New team name")},modifier=Modifier.fillMaxWidth());Button({scope.launch{withContext(Dispatchers.IO){svc.createTeam(name)};name="";reload()}},enabled=name.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text("Create team")}};items(teams){team->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text(team.team.name,style=MaterialTheme.typography.titleMedium);techs.forEach{t->val member=team.members.find{it.first.technicianId==t.technicianId};Row{Checkbox(member!=null,{checked->scope.launch{withContext(Dispatchers.IO){svc.setTeamMember(team.team.id,t.technicianId,checked,false)};reload()}});Text(t.displayName,Modifier.weight(1f).padding(top=12.dp));Checkbox(member?.second==true,{leader->scope.launch{withContext(Dispatchers.IO){svc.setTeamMember(team.team.id,t.technicianId,true,leader)};reload()}},enabled=member!=null)}}}}}}}

@Composable internal fun CreateDispatchPackageScreen(padding:PaddingValues){
    val context=LocalContext.current;val svc=remember{service(context)};val db=(context.applicationContext as ServiceLoopApplication).container.database;val scope=rememberCoroutineScope()
    var outbox by remember{mutableStateOf(emptyList<com.v16studio.serviceloop.data.DispatchOutboxVisitEntity>())};var teams by remember{mutableStateOf(emptyList<com.v16studio.serviceloop.data.DispatchTeamDetail>())};var sites by remember{mutableStateOf(emptyList<com.v16studio.serviceloop.data.SiteEntity>())};var equipment by remember{mutableStateOf(emptyList<com.v16studio.serviceloop.data.EquipmentEntity>())};var itemCounts by remember{mutableStateOf(emptyMap<String,Int>())}
    var sender by rememberSaveable{mutableStateOf("")};var manager by rememberSaveable{mutableStateOf("")};var date by rememberSaveable{mutableStateOf(LocalDate.now().plusDays(1).toString())};var time by rememberSaveable{mutableStateOf("09:00")};var zone by rememberSaveable{mutableStateOf(ZoneId.systemDefault().id)};var instructions by rememberSaveable{mutableStateOf("")};var siteId by rememberSaveable{mutableStateOf("")};var selectedTeams by remember{mutableStateOf(setOf<String>())};var selectedVisit by remember{mutableStateOf<String?>(null)}
    var task by rememberSaveable{mutableStateOf("")};var planRef by rememberSaveable{mutableStateOf("")};var due by rememberSaveable{mutableStateOf("")};var equipmentId by rememberSaveable{mutableStateOf("")};var assignees by remember{mutableStateOf(setOf<String>())};var editingItem by remember{mutableStateOf<String?>(null)};var visitItems by remember{mutableStateOf(emptyList<Pair<com.v16studio.serviceloop.data.DispatchOutboxItemEntity,List<String>>>())};var error by remember{mutableStateOf<String?>(null)}
    fun reload(){scope.launch{withContext(Dispatchers.IO){outbox=svc.outboxVisits();teams=svc.teams();sites=db.serviceLoopDao().allSites();equipment=db.serviceLoopDao().allEquipment();itemCounts=outbox.associate{it.dispatchVisitId to svc.outboxItems(it.dispatchVisitId).size};selectedVisit?.let{visitItems=svc.outboxItems(it)}}}}
    fun loadVisit(v:com.v16studio.serviceloop.data.DispatchOutboxVisitEntity){scope.launch{val loaded=withContext(Dispatchers.IO){svc.outboxTeamIds(v.dispatchVisitId) to svc.outboxItems(v.dispatchVisitId)};selectedVisit=v.dispatchVisitId;manager=v.managerReference.orEmpty();date=v.serviceDate;time=v.appointmentLocalTime.orEmpty();zone=v.appointmentZoneId;instructions=v.instructions.orEmpty();siteId=v.siteId;selectedTeams=loaded.first.toSet();visitItems=loaded.second;editingItem=null;task="";planRef="";due="";assignees=emptySet();equipmentId=""}}
    LaunchedEffect(Unit){reload()}
    val participants=teams.filter{it.team.id in selectedTeams}.flatMap{it.members}.distinctBy{it.first.technicianId}
    LazyColumn(Modifier.padding(padding).testTag("dispatch-outbox"),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
        item{Text("Dispatch outbox",style=MaterialTheme.typography.headlineSmall);Text("Durable central Visit definitions. They do not create planner Visits on this device.");OutlinedTextField(sender,{sender=it},label={Text("Sender label")},modifier=Modifier.fillMaxWidth());Text("Customer / Site");sites.forEach{s->FilterChip(siteId==s.id,{siteId=s.id;equipmentId=""},{Text("${s.reference} · ${s.name}")},Modifier.testTag("dispatch-site-${s.id}"))};OutlinedTextField(date,{date=it},label={Text("Service date · YYYY-MM-DD")},modifier=Modifier.fillMaxWidth());OutlinedTextField(time,{time=it},label={Text("Appointment time · Optional")},modifier=Modifier.fillMaxWidth());OutlinedTextField(zone,{zone=it},label={Text("ZoneId")},modifier=Modifier.fillMaxWidth());OutlinedTextField(manager,{manager=it},label={Text("Manager reference")},modifier=Modifier.fillMaxWidth());OutlinedTextField(instructions,{instructions=it},label={Text("Dispatch instructions")},modifier=Modifier.fillMaxWidth());Text("Teams · select one or more");teams.forEach{team->FilterChip(team.team.id in selectedTeams,{selectedTeams=if(team.team.id in selectedTeams)selectedTeams-team.team.id else selectedTeams+team.team.id},{Text(team.team.name)},Modifier.testTag("dispatch-team-${team.team.id}"))};Button({scope.launch{runCatching{withContext(Dispatchers.IO){val id=selectedVisit;if(id==null)svc.createOutboxVisit(manager,siteId,date,time.ifBlank{null},zone,instructions,selectedTeams.toList()) else{svc.updateOutboxVisit(id,manager,siteId,date,time.ifBlank{null},zone,instructions,selectedTeams.toList());id}}}.onSuccess{selectedVisit=it;reload()}.onFailure{if(it is CancellationException)throw it else error=it.message}}},enabled=siteId.isNotBlank()&&selectedTeams.isNotEmpty()&&runCatching{LocalDate.parse(date);ZoneId.of(zone)}.isSuccess,modifier=Modifier.fillMaxWidth().testTag("dispatch-save-visit")){Text(if(selectedVisit==null)"Create outbox Visit" else "Save Visit")}}
        if(selectedVisit!=null)item{Text("Work items",style=MaterialTheme.typography.titleLarge);visitItems.forEach{(existing,assigned)->Card(Modifier.fillMaxWidth().testTag("dispatch-item-${existing.dispatchItemId}")){Column(Modifier.padding(8.dp)){Text("${existing.taskName} · ${if(assigned.isEmpty())"Everyone" else "${assigned.size} assigned"}");TextButton({editingItem=existing.dispatchItemId;equipmentId=existing.equipmentId;task=existing.taskName;planRef=existing.servicePlanReference.orEmpty();due=existing.dueDateSnapshot.orEmpty();assignees=assigned.toSet()}){Text("Edit item")}}}};Text("Equipment at selected Site");equipment.filter{it.siteId==siteId}.forEach{eq->FilterChip(equipmentId==eq.id,{equipmentId=eq.id},{Text("${eq.reference} · ${eq.name}")},Modifier.testTag("dispatch-equipment-${eq.id}"))};OutlinedTextField(task,{task=it},label={Text("Task name")},modifier=Modifier.fillMaxWidth());OutlinedTextField(planRef,{planRef=it},label={Text("Local service plan reference · Optional")},modifier=Modifier.fillMaxWidth());OutlinedTextField(due,{due=it},label={Text("Due snapshot · Optional YYYY-MM-DD")},modifier=Modifier.fillMaxWidth());Text("Assigned technicians");Text("None selected = everyone on the selected teams",style=MaterialTheme.typography.bodySmall);participants.forEach{(tech,leader)->FilterChip(tech.technicianId in assignees,{assignees=if(tech.technicianId in assignees)assignees-tech.technicianId else assignees+tech.technicianId},{Text(tech.displayName+if(leader)" · Leader" else "")},Modifier.testTag("dispatch-assignee-${tech.technicianId}"))};Button({val visit=selectedVisit!!;scope.launch{runCatching{withContext(Dispatchers.IO){val item=editingItem;if(item==null)svc.addOutboxItem(visit,equipmentId,task,planRef.ifBlank{null},due.ifBlank{null},assignees.toList()) else{svc.updateOutboxItem(item,equipmentId,task,planRef.ifBlank{null},due.ifBlank{null},assignees.toList());item}}}.onSuccess{editingItem=null;task="";planRef="";due="";assignees=emptySet();reload()}.onFailure{if(it is CancellationException)throw it else error=it.message}}},enabled=equipmentId.isNotBlank()&&task.isNotBlank(),modifier=Modifier.fillMaxWidth().testTag("dispatch-add-item")){Text(if(editingItem!=null)"Save item" else if(assignees.isEmpty())"Add item · Everyone" else "Add assigned item")}}
        item{Button({scope.launch{runCatching{withContext(Dispatchers.IO){DispatchPackageCodec.encode(svc.exportPackage(outbox.map{it.dispatchVisitId},sender))}}.onSuccess{shareFile(context,"work-packages","serviceloop-dispatch.slwork",WORK_PACKAGE_MIME,it,"Share ServiceLoop work package")}.onFailure{if(it is CancellationException)throw it else error=it.message}}},enabled=sender.isNotBlank()&&outbox.isNotEmpty()&&itemCounts.values.any{it>0},modifier=Modifier.fillMaxWidth()){Text("Export all outbox Visits")};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}
        items(outbox){v->Card(Modifier.fillMaxWidth().testTag("dispatch-outbox-visit-${v.dispatchVisitId}")){Column(Modifier.padding(12.dp)){Text("${v.managerReference?:v.dispatchVisitId.take(8)} · ${v.serviceDate}");Text("${itemCounts[v.dispatchVisitId]?:0} items · Last exported generation ${v.lastExportedGeneration?:"Not exported"}");if(v.lastExportedGeneration!=null)Text("Material changes produce generation ${v.lastExportedGeneration+1} when exported.");TextButton({loadVisit(v)}){Text(if(selectedVisit==v.dispatchVisitId)"Editing" else "Edit Visit")}}}}
    }
}

@Composable internal fun ImportDispatchPackageScreen(padding:PaddingValues,nav:NavHostController,viewModel:ServiceLoopViewModel){
    val context=LocalContext.current;val svc=remember{service(context)};val scope=rememberCoroutineScope();var preview by remember{mutableStateOf<com.v16studio.serviceloop.data.DispatchPreview?>(null)};var error by remember{mutableStateOf<String?>(null)};var busy by remember{mutableStateOf(false)};var result by remember{mutableStateOf<String?>(null)}
    val open=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->uri?.let{scope.launch{busy=true;runCatching{withContext(Dispatchers.IO){val bytes=context.contentResolver.openInputStream(it)!!.use{x->x.readBounded(DispatchPackageCodec.MAX_BYTES)};svc.preview(DispatchPackageCodec.decode(bytes))}}.onSuccess{preview=it}.onFailure{if(it is CancellationException)throw it else error=it.message};busy=false}}}
    LazyColumn(Modifier.padding(padding).testTag("dispatch-import"),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
        item{Text("Import work package",style=MaterialTheme.typography.headlineSmall);Text("Opening only validates and previews. Work packages are readable and not cryptographically signed.");Button({open.launch(arrayOf(WORK_PACKAGE_MIME,"application/json"))},Modifier.fillMaxWidth()){Text("Choose .slwork file")};if(busy)Text("Validating…");error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}
        preview?.let{p->item{Text("From ${p.value.senderLabel}\nPackage ${p.value.packageId}");Text("This Technician: ${p.identity.name}\n${p.identity.technicianId}")};items(p.directory){line->Column{Text("${line.reference} · ${line.classification.name.replace('_',' ').lowercase()} · ${line.detail}");if(line.classification==com.v16studio.serviceloop.data.DispatchClassification.POSSIBLE_DUPLICATE){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(line.duplicateDecision==DispatchDuplicateDecision.CREATE_SEPARATE,{preview=svc.resolveDuplicate(p,line.reference,DispatchDuplicateDecision.CREATE_SEPARATE)},{Text("Create separate")},Modifier.testTag("duplicate-create-${line.reference}"));FilterChip(line.duplicateDecision==DispatchDuplicateDecision.SKIP_BRANCH,{preview=svc.resolveDuplicate(p,line.reference,DispatchDuplicateDecision.SKIP_BRANCH)},{Text("Skip branch")},Modifier.testTag("duplicate-skip-${line.reference}"))}}}};items(p.visits){v->Card(Modifier.fillMaxWidth().testTag("dispatch-preview-${v.dispatchVisitId}")){Column(Modifier.padding(12.dp)){Text("${v.dispatchVisitId.take(8)} · generation ${v.generation}");Text(v.classification.name.replace('_',' ').lowercase());v.changes.forEach{Text("${it.label}: ${it.before} → ${it.after}")};v.items.forEach{Text("${it.taskName} · ${it.localRole.replace('_',' ').lowercase()} · ${it.change.replace('_',' ').lowercase()}")};v.reasons.forEach{Text(it,color=MaterialTheme.colorScheme.tertiary)}}}};item{Button({scope.launch{busy=true;runCatching{withContext(Dispatchers.IO){svc.import(p)}}.onSuccess{r->result="Created ${r.createdVisitIds.size} · Updated ${r.updatedVisitIds.size} · Unchanged ${r.unchangedVisitIds.size}";viewModel.loadVisits()}.onFailure{if(it is CancellationException)throw it else error=it.message};busy=false}},enabled=p.canImport&&!busy,modifier=Modifier.fillMaxWidth().testTag("import-dispatch-work")){Text("Apply assigned work")};result?.let{Text(it);OutlinedButton({nav.navigate(workRoute(WorkTab.VISITS))},Modifier.fillMaxWidth()){Text("View Visits")}}}}
    }
}

@Composable internal fun DispatchVisitPanel(detail:VisitDetail,modifier:Modifier=Modifier){
    val context=LocalContext.current;val svc=remember{service(context)};val scope=rememberCoroutineScope();var data by remember(detail.id){mutableStateOf<Pair<DispatchVisitBindingEntity,List<DispatchItemBindingEntity>>?>(null)};var message by remember{mutableStateOf<String?>(null)};var handoffItem by remember{mutableStateOf<DispatchItemBindingEntity?>(null)};var review by remember{mutableStateOf<HandoffReview?>(null)};var target by remember{mutableStateOf<DispatchTechnicianSnapshot?>(null)}
    fun reload(){scope.launch{data=withContext(Dispatchers.IO){svc.dispatchDetail(detail.id)}}};LaunchedEffect(detail.id){reload()}
    if(handoffItem!=null&&review!=null){val r=review!!;AlertDialog(modifier=Modifier.testTag("handoff-picker"),onDismissRequest={handoffItem=null;review=null;target=null},title={Text("Hand off documentation")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Choose an eligible recipient. This records your local documentation handoff. ServiceLoop cannot confirm that the selected Technician accepted it.");r.candidates.forEach{candidate->FilterChip(target?.technicianId==candidate.technicianId,{target=candidate},{Text(candidate.name)},Modifier.testTag("handoff-recipient-${candidate.technicianId}"))};if(r.hasSubstantiveDraft)Text("Your local answers, notes, parts, and draft photographs will be permanently removed from this draft.",color=MaterialTheme.colorScheme.error)}},dismissButton={TextButton({handoffItem=null;review=null;target=null}){Text("Cancel")}},confirmButton={Button({val selected=target?:return@Button;val item=handoffItem?:return@Button;scope.launch{runCatching{withContext(Dispatchers.IO){svc.handoff(detail.id,item.dispatchItemId,selected,r.hasSubstantiveDraft)}}.onSuccess{message="Documentation handed off locally to ${selected.name}; acceptance is not implied"}.onFailure{if(it is CancellationException)throw it else message=it.message};handoffItem=null;review=null;target=null;reload()}},enabled=target!=null,modifier=Modifier.testTag(if(r.hasSubstantiveDraft)"handoff-discard-confirm" else "handoff-confirm")){Text(if(r.hasSubstantiveDraft)"Discard my local documentation and hand off to ${target?.name.orEmpty()}" else "Hand off to ${target?.name.orEmpty()}")}})}
    data?.let{(binding,items)->Card(modifier.fillMaxWidth().testTag("dispatched-visit")){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Dispatched · generation ${binding.appliedGeneration}",style=MaterialTheme.typography.titleMedium);binding.managerReference?.let{Text("Job $it")};binding.instructionsSnapshot?.let{Text("Dispatch instructions\n$it",Modifier.testTag("dispatch-instructions"))};if(detail.state=="PARTICIPATION_COMPLETE")Text("Participation complete. This records only your local involvement; it does not mean the central job was cancelled, accepted, or reported.");if(detail.state=="DISPATCH_WITHDRAWN")Text("Dispatch assignment withdrawn by a newer generation. This is not a central cancellation.");items.forEach{i->Text("${i.taskNameSnapshot}\n${if(i.assignmentMeaning=="EVERYONE")"Assigned to everyone" else "Assigned technicians preserved"} · ${i.localRole.replace('_',' ').lowercase()} · ${i.documentationDisposition.replace('_',' ').lowercase()}");if(detail.state=="WORKING"){if(i.documentationDisposition in setOf("PENDING","LEADER_OBSERVE"))Button({scope.launch{message=withContext(Dispatchers.IO){svc.documentLocally(detail.id,i.dispatchItemId)};reload()}},Modifier.fillMaxWidth()){Text("Document this item")};if(i.localRole=="ASSIGNED"&&i.documentationDisposition!="DEFERRED"){OutlinedButton({scope.launch{runCatching{withContext(Dispatchers.IO){svc.handoffReview(detail.id,i.dispatchItemId)}}.onSuccess{r->handoffItem=i;review=r}.onFailure{message=it.message}}},Modifier.fillMaxWidth().testTag("handoff-open-${i.dispatchItemId}")){Text("Hand off documentation…")}};if(i.documentationDisposition=="DEFERRED")OutlinedButton({scope.launch{withContext(Dispatchers.IO){svc.undoHandoff(detail.id,i.dispatchItemId)};reload()}},Modifier.fillMaxWidth()){Text("Document this item myself")}}};if(detail.state=="WORKING"&&items.filter{it.localRole=="ASSIGNED"}.all{it.documentationDisposition=="DEFERRED"}&&items.none{it.documentationDisposition=="DOCUMENT_LOCAL"})Button({scope.launch{withContext(Dispatchers.IO){svc.finishInvolvement(detail.id)};reload()}},Modifier.fillMaxWidth()){Text("Finish my involvement")};message?.let{Text(it,color=MaterialTheme.colorScheme.primary)}}}}
}
