package com.v16studio.serviceloop.ui

import android.content.Context
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.unit.dp
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.compose.LocalLifecycleOwner
import androidx.navigation.NavHostController
import com.v16studio.serviceloop.ServiceLoopApplication
import com.v16studio.serviceloop.data.*
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.LocalTime
import java.time.ZoneId
import java.time.temporal.TemporalAdjusters
import java.util.UUID
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

private fun dispatchService(context:Context)=DispatchPackageService((context.applicationContext as ServiceLoopApplication).container.database,context.filesDir)

@Composable private fun DispatchChoiceDialog(title:String,options:List<String>,selected:String,onDismiss:()->Unit,onSelect:(String)->Unit){
    AlertDialog(onDismissRequest=onDismiss,title={Text(title)},text={Column{options.forEach{option->TextButton({onSelect(option)},Modifier.fillMaxWidth().testTag("dispatch-choice-${option.lowercase().replace(' ','-')}")){Text((if(option==selected)"✓ " else "")+option)}}}},confirmButton={TextButton(onDismiss){Text("Cancel")}})
}

@Composable internal fun DispatchOutboxScreen(padding:PaddingValues,nav:NavHostController,serviceOverride:DispatchPackageService?=null,databaseOverride:ServiceLoopDatabase?=null){
    val context=LocalContext.current;val svc=remember(serviceOverride){serviceOverride?:dispatchService(context)};val db=databaseOverride?:(context.applicationContext as ServiceLoopApplication).container.database;val scope=rememberCoroutineScope();val lifecycleOwner=LocalLifecycleOwner.current
    var outbox by remember{mutableStateOf(emptyList<DispatchOutboxVisitEntity>())};var sites by remember{mutableStateOf(emptyList<SiteEntity>())};var customers by remember{mutableStateOf(emptyList<CustomerEntity>())};var itemCounts by remember{mutableStateOf(emptyMap<String,Int>())}
    var search by rememberSaveable{mutableStateOf("")};var statusFilter by rememberSaveable{mutableStateOf("Active")};var dateFilter by rememberSaveable{mutableStateOf("All dates")};var customStart by rememberSaveable{mutableStateOf(LocalDate.now().toString())};var customEnd by rememberSaveable{mutableStateOf(LocalDate.now().plusDays(7).toString())};var checked by remember{mutableStateOf(setOf<String>())};var choice by remember{mutableStateOf<String?>(null)};var pendingStatusAction by remember{mutableStateOf<String?>(null)};var error by remember{mutableStateOf<String?>(null)}
    fun reload(){scope.launch{withContext(Dispatchers.IO){outbox=svc.outboxVisits();sites=db.serviceLoopDao().allSites();customers=db.serviceLoopDao().allCustomers();itemCounts=outbox.associate{it.dispatchVisitId to svc.outboxItems(it.dispatchVisitId).size}}}}
    LaunchedEffect(Unit){reload()};DisposableEffect(lifecycleOwner){val observer=LifecycleEventObserver{_,event->if(event==Lifecycle.Event.ON_RESUME)reload()};lifecycleOwner.lifecycle.addObserver(observer);onDispose{lifecycleOwner.lifecycle.removeObserver(observer)}}
    val today=LocalDate.now();val monday=today.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));val customRange=runCatching{LocalDate.parse(customStart)..LocalDate.parse(customEnd)}.getOrNull();val siteMap=sites.associateBy{it.id};val customerMap=customers.associateBy{it.id};val needle=search.trim().lowercase()
    val visible=outbox.filter{visit->val statusMatch=when(statusFilter){"Active"->visit.outboxStatus!=DispatchOutboxStatus.CONCLUDED;"Draft"->visit.outboxStatus==DispatchOutboxStatus.DRAFT;"Dispatched"->visit.outboxStatus==DispatchOutboxStatus.DISPATCHED;"Concluded"->visit.outboxStatus==DispatchOutboxStatus.CONCLUDED;else->true};val date=LocalDate.parse(visit.serviceDate);val dateMatch=when(dateFilter){"Today"->date==today;"Tomorrow"->date==today.plusDays(1);"This week"->date in monday..monday.plusDays(6);"Next 7 days"->date in today..today.plusDays(6);"Custom range"->customRange?.let{date in it}==true;else->true};val site=siteMap[visit.siteId];val customer=site?.let{customerMap[it.customerId]};val searchMatch=needle.isEmpty()||listOf(visit.managerReference,site?.reference,site?.name,customer?.reference,customer?.name).any{it?.lowercase()?.contains(needle)==true};statusMatch&&dateMatch&&searchMatch}.sortedWith(compareBy({it.serviceDate},{it.appointmentLocalTime.orEmpty()},{it.createdAtEpochMillis},{it.dispatchVisitId}))
    LaunchedEffect(visible.map{it.dispatchVisitId}){checked=checked.intersect(visible.map{it.dispatchVisitId}.toSet())};val selectedRows=visible.filter{it.dispatchVisitId in checked}
    choice?.let{kind->val options=if(kind=="status")listOf("Active","Draft","Dispatched","Concluded","All")else listOf("Today","Tomorrow","This week","Next 7 days","Custom range","All dates");DispatchChoiceDialog(if(kind=="status")"Status" else "Service date",options,if(kind=="status")statusFilter else dateFilter,{choice=null}){value->if(kind=="status")statusFilter=value else dateFilter=value;choice=null}}
    pendingStatusAction?.let{action->AlertDialog(modifier=Modifier.testTag("dispatch-status-confirm"),onDismissRequest={pendingStatusAction=null},title={Text(if(action=="conclude")"Mark ${selectedRows.size} dispatched Visits as concluded?" else "Reopen ${selectedRows.size} concluded Visits?")},text={Text(if(action=="conclude")"This closes them only in this coordinator Outbox. Technician devices are not updated." else "Reopened Visits return to Dispatched. Export history and generation are preserved.")},dismissButton={TextButton({pendingStatusAction=null}){Text("Cancel")}},confirmButton={Button({val ids=selectedRows.map{it.dispatchVisitId};scope.launch{runCatching{withContext(Dispatchers.IO){if(action=="conclude")svc.concludeOutboxVisits(ids)else svc.reopenOutboxVisits(ids)}}.onSuccess{checked=emptySet();pendingStatusAction=null;reload()}.onFailure{if(it is CancellationException)throw it else error=it.message;pendingStatusAction=null}}},Modifier.testTag("dispatch-status-confirm-action")){Text(if(action=="conclude")"Mark concluded" else "Reopen")}})}
    Column(Modifier.padding(padding).fillMaxSize().testTag("dispatch-outbox")){
        Column(Modifier.fillMaxWidth().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){
            Text("Dispatch outbox",style=MaterialTheme.typography.headlineSmall)
            Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({nav.navigate("dispatch/visit/new")},Modifier.weight(1f).testTag("dispatch-new-visit")){Text("New visit")};OutlinedButton({checked=visible.map{it.dispatchVisitId}.toSet()},Modifier.weight(1f).testTag("dispatch-select-all")){Text("Select all shown")}}
            OutlinedTextField(search,{search=it},label={Text("Search Visits")},singleLine=true,modifier=Modifier.fillMaxWidth().testTag("dispatch-search"))
            Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({choice="status"},Modifier.weight(1f).testTag("dispatch-status-filter")){Text("Status: $statusFilter")};OutlinedButton({choice="date"},Modifier.weight(1f).testTag("dispatch-date-filter")){Text("Date: $dateFilter")}}
            if(dateFilter=="Custom range")Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(customStart,{customStart=it},label={Text("From")},singleLine=true,modifier=Modifier.weight(1f));OutlinedTextField(customEnd,{customEnd=it},label={Text("Through")},singleLine=true,modifier=Modifier.weight(1f))}
            if(selectedRows.isNotEmpty())Column(Modifier.fillMaxWidth().testTag("dispatch-batch-actions"),verticalArrangement=Arrangement.spacedBy(6.dp)){
                Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text("${selectedRows.size} selected",Modifier.weight(1f).testTag("dispatch-selected-count"));TextButton({checked=emptySet()},Modifier.testTag("dispatch-clear-selection")){Text("Clear")}}
                Button({when{selectedRows.size>DispatchPackageCodec.MAX_VISITS->error="A work package can contain at most ${DispatchPackageCodec.MAX_VISITS} Visits. Reduce the selection.";selectedRows.any{it.outboxStatus==DispatchOutboxStatus.CONCLUDED}->error="Concluded Visits must be reopened before export.";selectedRows.any{(itemCounts[it.dispatchVisitId]?:0)==0}->error="Every selected Visit needs at least one work item before export.";else->{nav.currentBackStackEntry?.savedStateHandle?.set("dispatch-export-ids",ArrayList(selectedRows.map{it.dispatchVisitId}));nav.navigate("dispatch/export-review")}}},Modifier.fillMaxWidth().testTag("dispatch-export-selected")){Text("Export selected (${selectedRows.size})")}
                if(selectedRows.all{it.outboxStatus==DispatchOutboxStatus.DISPATCHED})OutlinedButton({pendingStatusAction="conclude"},Modifier.fillMaxWidth().testTag("dispatch-conclude-selected")){Text("Mark concluded (${selectedRows.size})")}
                if(selectedRows.all{it.outboxStatus==DispatchOutboxStatus.CONCLUDED})OutlinedButton({pendingStatusAction="reopen"},Modifier.fillMaxWidth().testTag("dispatch-reopen-selected")){Text("Reopen (${selectedRows.size})")}
                if(selectedRows.map{it.outboxStatus}.toSet().size>1)Text("Mixed statuses cannot use a partial status action.",style=MaterialTheme.typography.bodySmall)
            }
            error?.let{Text(it,color=MaterialTheme.colorScheme.error)}
        }
        LazyColumn(Modifier.weight(1f).fillMaxWidth().testTag("dispatch-outbox-list"),contentPadding=PaddingValues(16.dp,0.dp,16.dp,24.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
            if(outbox.isEmpty())item{Text("No Dispatch Visits yet.");TextButton({nav.navigate("dispatch/visit/new")}){Text("New visit")}}
            else if(visible.isEmpty())item{Text(if(search.isNotBlank())"No matching Dispatch Visits." else "No Visits match these filters.")}
            items(visible,key={it.dispatchVisitId}){visit->val site=siteMap[visit.siteId];val customer=site?.let{customerMap[it.customerId]};Card(Modifier.fillMaxWidth().testTag("dispatch-outbox-visit-${visit.dispatchVisitId}")){Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.Top){Checkbox(visit.dispatchVisitId in checked,{isChecked->checked=if(isChecked)checked+visit.dispatchVisitId else checked-visit.dispatchVisitId},Modifier.testTag("dispatch-select-${visit.dispatchVisitId}"));Column(Modifier.weight(1f).clickable{nav.navigate("dispatch/visit/${visit.dispatchVisitId}")}.testTag("dispatch-open-${visit.dispatchVisitId}")){Text("${visit.serviceDate}${visit.appointmentLocalTime?.let{" · $it"}.orEmpty()}");Text("${visit.managerReference?:visit.dispatchVisitId.take(8)} · ${site?.reference.orEmpty()} ${site?.name?:"Unknown Site"}");customer?.let{Text(it.name,style=MaterialTheme.typography.bodySmall)};Text("${itemCounts[visit.dispatchVisitId]?:0} work items · ${visit.outboxStatus.name.lowercase().replaceFirstChar{it.uppercase()}}${visit.lastExportedGeneration?.let{" · Generation $it"}.orEmpty()}");if((itemCounts[visit.dispatchVisitId]?:0)==0)Text("Needs a work item before export",color=MaterialTheme.colorScheme.error,style=MaterialTheme.typography.bodySmall)}}}}
        }
    }
}

@Composable internal fun DispatchSitePickerDialog(sites:List<SiteEntity>,customers:List<CustomerEntity>,onDismiss:()->Unit,onSelect:(String)->Unit){
    var query by rememberSaveable{mutableStateOf("")};val customersById=customers.associateBy{it.id};val needle=query.trim().lowercase();val results=sites.filter{site->val customer=customersById[site.customerId];needle.isEmpty()||listOf(site.reference,site.name,site.address,customer?.reference,customer?.name).any{it?.lowercase()?.contains(needle)==true}}
    AlertDialog(modifier=Modifier.testTag("dispatch-site-picker"),onDismissRequest=onDismiss,title={Text("Choose Site")},text={Column{OutlinedTextField(query,{query=it},label={Text("Search Site, Customer, or address")},singleLine=true,modifier=Modifier.fillMaxWidth().testTag("dispatch-site-search"));LazyColumn(Modifier.heightIn(max=420.dp)){items(results,key={it.id}){site->val customer=customersById[site.customerId];TextButton({onSelect(site.id)},Modifier.fillMaxWidth().testTag("dispatch-site-${site.id}")){Column(Modifier.fillMaxWidth()){Text("${site.reference} · ${site.name}");Text(listOfNotNull(customer?.name,site.address).joinToString(" · "),style=MaterialTheme.typography.bodySmall)}}};if(results.isEmpty())item{Text("No matching Sites.",Modifier.padding(top=12.dp))}}}},confirmButton={TextButton(onDismiss){Text("Cancel")}})
}

@Composable private fun DispatchTeamPickerDialog(teams:List<DispatchTeamDetail>,selected:Set<String>,onDismiss:()->Unit,onApply:(Set<String>)->Unit){
    var staged by remember(selected){mutableStateOf(selected)}
    AlertDialog(modifier=Modifier.testTag("dispatch-team-picker"),onDismissRequest=onDismiss,title={Text("Choose Teams")},text={LazyColumn(Modifier.heightIn(max=420.dp)){items(teams,key={it.team.id}){team->Row(Modifier.fillMaxWidth().clickable{staged=if(team.team.id in staged)staged-team.team.id else staged+team.team.id},verticalAlignment=Alignment.CenterVertically){Checkbox(team.team.id in staged,null);Column{Text(team.team.name);Text("${team.members.size} members",style=MaterialTheme.typography.bodySmall)}}};if(teams.isEmpty())item{Text("Create a Team in Coordinator tools first.")}}},dismissButton={TextButton(onDismiss){Text("Cancel")}},confirmButton={Button({onApply(staged)},Modifier.testTag("dispatch-team-apply")){Text("Apply")}})
}

@Composable private fun DispatchWorkItemDialog(existing:DispatchOutboxItemDraft?,equipment:List<EquipmentEntity>,participants:List<DispatchTechnicianEntity>,onDismiss:()->Unit,onSave:(DispatchOutboxItemDraft)->Unit){
    var equipmentId by remember(existing){mutableStateOf(existing?.equipmentId.orEmpty())};var task by remember(existing){mutableStateOf(existing?.taskName.orEmpty())};var plan by remember(existing){mutableStateOf(existing?.servicePlanReference.orEmpty())};var due by remember(existing){mutableStateOf(existing?.dueDateSnapshot.orEmpty())};var assigned by remember(existing){mutableStateOf(existing?.assignedTechnicianIds?.toSet().orEmpty())};var error by remember{mutableStateOf<String?>(null)}
    AlertDialog(modifier=Modifier.testTag("dispatch-work-item-editor"),onDismissRequest=onDismiss,title={Text(if(existing==null)"Add work item" else "Edit work item")},text={LazyColumn(Modifier.heightIn(max=500.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text("Equipment at selected Site")};items(equipment,key={it.id}){value->FilterChip(equipmentId==value.id,{equipmentId=value.id},{Text("${value.reference} · ${value.name}")},Modifier.fillMaxWidth().testTag("dispatch-equipment-${value.id}"))};item{OutlinedTextField(task,{task=it},label={Text("Task name")},modifier=Modifier.fillMaxWidth().testTag("dispatch-work-task"));OutlinedTextField(plan,{plan=it},label={Text("Local Service Plan reference · Optional")},modifier=Modifier.fillMaxWidth());OutlinedTextField(due,{due=it},label={Text("Due snapshot · Optional YYYY-MM-DD")},modifier=Modifier.fillMaxWidth());Text("Assignment");Text("No selected Technician means Everyone on the selected Teams.",style=MaterialTheme.typography.bodySmall);participants.forEach{tech->Row(Modifier.fillMaxWidth().clickable{assigned=if(tech.technicianId in assigned)assigned-tech.technicianId else assigned+tech.technicianId},verticalAlignment=Alignment.CenterVertically){Checkbox(tech.technicianId in assigned,null);Text(tech.displayName)}};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}}},dismissButton={TextButton(onDismiss){Text("Cancel")}},confirmButton={Button({when{equipmentId.isBlank()->error="Choose Equipment.";task.isBlank()->error="Enter a task name.";due.isNotBlank()&&runCatching{LocalDate.parse(due)}.isFailure->error="Enter due date as YYYY-MM-DD.";else->onSave(DispatchOutboxItemDraft(existing?.dispatchItemId?:UUID.randomUUID().toString(),equipmentId,task,plan.ifBlank{null},due.ifBlank{null},assigned.toList()))}},Modifier.testTag("dispatch-work-item-save")){Text("Save item")}})
}

private data class DispatchEditorLoad(
    val sites:List<SiteEntity>,val customers:List<CustomerEntity>,val equipment:List<EquipmentEntity>,val teams:List<DispatchTeamDetail>,
    val visit:DispatchOutboxVisitEntity?,val teamIds:List<String>,val items:List<DispatchOutboxItemDraft>,
)

@Composable internal fun DispatchVisitEditorScreen(padding:PaddingValues,nav:NavHostController,visitId:String?,serviceOverride:DispatchPackageService?=null,databaseOverride:ServiceLoopDatabase?=null){
    val context=LocalContext.current;val svc=remember(serviceOverride){serviceOverride?:dispatchService(context)};val db=databaseOverride?:(context.applicationContext as ServiceLoopApplication).container.database;val scope=rememberCoroutineScope()
    var sites by remember{mutableStateOf(emptyList<SiteEntity>())};var customers by remember{mutableStateOf(emptyList<CustomerEntity>())};var equipment by remember{mutableStateOf(emptyList<EquipmentEntity>())};var teams by remember{mutableStateOf(emptyList<DispatchTeamDetail>())};var loadedVisit by remember{mutableStateOf<DispatchOutboxVisitEntity?>(null)}
    var manager by rememberSaveable(visitId){mutableStateOf("")};var date by rememberSaveable(visitId){mutableStateOf(LocalDate.now().plusDays(1).toString())};var time by rememberSaveable(visitId){mutableStateOf("09:00")};var zone by rememberSaveable(visitId){mutableStateOf(ZoneId.systemDefault().id)};var instructions by rememberSaveable(visitId){mutableStateOf("")};var siteId by rememberSaveable(visitId){mutableStateOf("")};var selectedTeams by remember{mutableStateOf(setOf<String>())};var stagedItems by remember{mutableStateOf(emptyList<DispatchOutboxItemDraft>())}
    var initialized by remember{mutableStateOf(false)};var initialDraft by remember{mutableStateOf<DispatchOutboxEditorDraft?>(null)};var showSites by remember{mutableStateOf(false)};var showTeams by remember{mutableStateOf(false)};var showWorkItem by remember{mutableStateOf(false)};var editingItem by remember{mutableStateOf<DispatchOutboxItemDraft?>(null)};var pendingSite by remember{mutableStateOf<String?>(null)};var error by remember{mutableStateOf<String?>(null)};var busy by remember{mutableStateOf(false)}
    fun currentDraft()=DispatchOutboxEditorDraft(visitId,loadedVisit?.modifiedAtEpochMillis,manager,siteId,date,time.ifBlank{null},zone,instructions,selectedTeams.toList().sorted(),stagedItems)
    fun load(){scope.launch{val data=withContext(Dispatchers.IO){val visit=visitId?.let{id->svc.outboxVisits().find{it.dispatchVisitId==id}};DispatchEditorLoad(db.serviceLoopDao().allSites(),db.serviceLoopDao().allCustomers(),db.serviceLoopDao().allEquipment(),svc.teams(),visit,visitId?.let{svc.outboxTeamIds(it)}.orEmpty(),visitId?.let{svc.outboxItems(it)}.orEmpty().map{(item,assigned)->DispatchOutboxItemDraft(item.dispatchItemId,item.equipmentId,item.taskName,item.servicePlanReference,item.dueDateSnapshot,assigned)})};sites=data.sites;customers=data.customers;equipment=data.equipment;teams=data.teams;loadedVisit=data.visit;selectedTeams=data.teamIds.toSet();stagedItems=data.items;data.visit?.let{manager=it.managerReference.orEmpty();date=it.serviceDate;time=it.appointmentLocalTime.orEmpty();zone=it.appointmentZoneId;instructions=it.instructions.orEmpty();siteId=it.siteId};initialized=true;initialDraft=currentDraft()}}
    LaunchedEffect(visitId){load()}
    val readOnly=loadedVisit?.outboxStatus==DispatchOutboxStatus.CONCLUDED;val changed=initialized&&initialDraft!=currentDraft();UnsavedChangesGuard(changed,nav)
    val siteMap=sites.associateBy{it.id};val customerMap=customers.associateBy{it.id};val chosenSite=siteMap[siteId];val participants=teams.filter{it.team.id in selectedTeams}.flatMap{it.members.map{member->member.first}}.distinctBy{it.technicianId};val equipmentAtSite=equipment.filter{it.siteId==siteId}
    if(showSites)DispatchSitePickerDialog(sites,customers,{showSites=false}){newSite->if(newSite!=siteId&&stagedItems.isNotEmpty())pendingSite=newSite else siteId=newSite;showSites=false}
    pendingSite?.let{newSite->AlertDialog(onDismissRequest={pendingSite=null},title={Text("Change Site and remove work items?")},text={Text("Existing work items use Equipment from the current Site. Changing Site will remove all staged work items; Equipment is never silently retargeted.")},dismissButton={TextButton({pendingSite=null}){Text("Keep current Site")}},confirmButton={Button({siteId=newSite;stagedItems=emptyList();pendingSite=null}){Text("Remove items and change Site")}})}
    if(showTeams)DispatchTeamPickerDialog(teams,selectedTeams,{showTeams=false}){newTeams->val allowed=teams.filter{it.team.id in newTeams}.flatMap{it.members}.map{it.first.technicianId}.toSet();if(stagedItems.any{item->item.assignedTechnicianIds.any{it !in allowed}}){error="Update item assignments before removing those Team members.";showTeams=false} else{selectedTeams=newTeams;showTeams=false}}
    if(showWorkItem)DispatchWorkItemDialog(editingItem,equipmentAtSite,participants,{showWorkItem=false;editingItem=null}){item->stagedItems=if(editingItem==null)stagedItems+item else stagedItems.map{if(it.dispatchItemId==item.dispatchItemId)item else it};showWorkItem=false;editingItem=null}
    LazyColumn(Modifier.padding(padding).fillMaxSize().testTag(if(visitId==null)"dispatch-new-visit" else "dispatch-visit-editor"),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
        item{Text(if(visitId==null)"New Dispatch Visit" else if(readOnly)"View concluded Dispatch Visit" else "Edit Dispatch Visit",style=MaterialTheme.typography.headlineSmall);loadedVisit?.let{Text("${it.outboxStatus.name.lowercase().replaceFirstChar{x->x.uppercase()}}${it.lastExportedGeneration?.let{x->" · Generation $x"}.orEmpty()}")};if(loadedVisit?.outboxStatus==DispatchOutboxStatus.DISPATCHED)Text("Material changes create a later generation only when this Visit is exported again.",style=MaterialTheme.typography.bodySmall);if(readOnly)Text("Concluded is read-only. Reopen it before editing.")}
        item{Text("Site / Customer",style=MaterialTheme.typography.titleMedium);Text(chosenSite?.let{site->"${site.reference} · ${site.name}\n${customerMap[site.customerId]?.name.orEmpty()}"}?:"No Site selected");OutlinedButton({showSites=true},Modifier.fillMaxWidth().testTag("dispatch-choose-site"),enabled=!readOnly){Text(if(chosenSite==null)"Choose Site" else "Change Site")}}
        item{Text("Appointment",style=MaterialTheme.typography.titleMedium);OutlinedTextField(date,{date=it},label={Text("Service date · YYYY-MM-DD")},enabled=!readOnly,modifier=Modifier.fillMaxWidth());OutlinedTextField(time,{time=it},label={Text("Appointment time · Optional")},enabled=!readOnly,modifier=Modifier.fillMaxWidth());OutlinedTextField(zone,{zone=it},label={Text("ZoneId")},enabled=!readOnly,modifier=Modifier.fillMaxWidth());OutlinedTextField(manager,{manager=it},label={Text("Manager reference")},enabled=!readOnly,modifier=Modifier.fillMaxWidth());OutlinedTextField(instructions,{instructions=it},label={Text("Dispatch instructions")},enabled=!readOnly,modifier=Modifier.fillMaxWidth())}
        item{Text("Teams",style=MaterialTheme.typography.titleMedium);Text(if(selectedTeams.isEmpty())"No Teams selected" else teams.filter{it.team.id in selectedTeams}.joinToString{it.team.name});OutlinedButton({showTeams=true},Modifier.fillMaxWidth().testTag("dispatch-choose-teams"),enabled=!readOnly){Text(if(selectedTeams.isEmpty())"Choose Teams" else "Change Teams")}}
        item{Text("Work items",style=MaterialTheme.typography.titleMedium);if(stagedItems.isEmpty())Text("No work items yet. This Draft will not be export-ready.");stagedItems.forEach{item->val eq=equipment.find{it.id==item.equipmentId};Card(Modifier.fillMaxWidth().testTag("dispatch-item-${item.dispatchItemId}")){Column(Modifier.padding(10.dp)){Text("${eq?.reference.orEmpty()} · ${eq?.name?:"Unknown Equipment"}");Text(item.taskName);Text(if(item.assignedTechnicianIds.isEmpty())"Everyone" else "${item.assignedTechnicianIds.size} assigned");if(!readOnly)Row{TextButton({editingItem=item;showWorkItem=true}){Text("Edit")};TextButton({stagedItems=stagedItems.filterNot{it.dispatchItemId==item.dispatchItemId}}){Text("Remove")}}}}};OutlinedButton({if(siteId.isBlank())error="Choose a Site before adding work." else{editingItem=null;showWorkItem=true}},Modifier.fillMaxWidth().testTag("dispatch-add-item"),enabled=!readOnly){Text("Add work item")}}
        item{error?.let{Text(it,color=MaterialTheme.colorScheme.error)};if(!readOnly)Button({error=null;when{siteId.isBlank()->error="Choose a Site.";selectedTeams.isEmpty()->error="Choose at least one Team.";participants.isEmpty()->error="Selected Teams need at least one Technician.";runCatching{LocalDate.parse(date)}.isFailure->error="Enter service date as YYYY-MM-DD.";time.isNotBlank()&&runCatching{LocalTime.parse(time)}.isFailure->error="Enter appointment time as HH:mm.";runCatching{ZoneId.of(zone)}.isFailure->error="Enter a valid ZoneId.";else->{busy=true;scope.launch{val result=runCatching{withContext(Dispatchers.IO){svc.saveOutboxVisit(currentDraft())}};withContext(Dispatchers.Main.immediate){result.onSuccess{initialDraft=currentDraft();nav.popBackStack()}.onFailure{if(it is CancellationException)throw it else error=it.message?:"Could not save this Dispatch Visit."};busy=false}}}}},Modifier.fillMaxWidth().testTag("dispatch-save-visit"),enabled=!busy){Text(if(visitId==null)"Save draft" else "Save")};if(loadedVisit?.outboxStatus==DispatchOutboxStatus.DISPATCHED)OutlinedButton({scope.launch{runCatching{withContext(Dispatchers.IO){svc.concludeOutboxVisits(listOf(visitId!!))}}.onSuccess{initialDraft=currentDraft();nav.popBackStack()}.onFailure{if(it is CancellationException)throw it else error=it.message}}},Modifier.fillMaxWidth().testTag("dispatch-conclude-visit"),enabled=!changed&&!busy){Text("Mark concluded")};if(loadedVisit?.outboxStatus==DispatchOutboxStatus.DISPATCHED&&changed)Text("Save or discard your edits before marking this Visit concluded.",style=MaterialTheme.typography.bodySmall);if(readOnly)Button({scope.launch{runCatching{withContext(Dispatchers.IO){svc.reopenOutboxVisits(listOf(visitId!!))}}.onSuccess{load()}.onFailure{if(it is CancellationException)throw it else error=it.message}}},Modifier.fillMaxWidth().testTag("dispatch-reopen-visit")){Text("Reopen")}}
    }
}

@Composable internal fun DispatchExportReviewScreen(padding:PaddingValues,nav:NavHostController,ids:List<String>,serviceOverride:DispatchPackageService?=null){
    val context=LocalContext.current;val svc=remember(serviceOverride){serviceOverride?:dispatchService(context)};val scope=rememberCoroutineScope();var sender by rememberSaveable{mutableStateOf("")};var prepared by remember{mutableStateOf<DispatchExportPreparation?>(null)};var currentGenerations by remember{mutableStateOf(emptyMap<String,Int?>())};var error by remember{mutableStateOf<String?>(null)};var refresh by remember{mutableStateOf(0)};var busy by remember{mutableStateOf(false)}
    LaunchedEffect(ids,sender,refresh){prepared=null;if(sender.isNotBlank())runCatching{withContext(Dispatchers.IO){svc.prepareExport(ids,sender) to svc.outboxVisits().filter{it.dispatchVisitId in ids}.associate{it.dispatchVisitId to it.lastExportedGeneration}}}.onSuccess{prepared=it.first;currentGenerations=it.second}.onFailure{if(it is CancellationException)throw it else error=it.message}}
    val visits=prepared?.packageValue?.visits.orEmpty();val itemCount=visits.sumOf{it.work.size};val first=visits.minOfOrNull{it.serviceDate};val last=visits.maxOfOrNull{it.serviceDate}
    LazyColumn(Modifier.padding(padding).fillMaxSize().testTag("dispatch-export-review"),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
        item{Text("Export review",style=MaterialTheme.typography.headlineSmall);Text("${ids.size} selected Visits");OutlinedTextField(sender,{sender=it;prepared=null;error=null},label={Text("Sender label")},modifier=Modifier.fillMaxWidth().testTag("dispatch-export-sender"));if(sender.isBlank())Text("Sender label is required before package creation.",color=MaterialTheme.colorScheme.error);if(prepared==null&&sender.isNotBlank())Text("Preparing non-mutating review…")}
        if(visits.isNotEmpty())item{Text("${visits.size} Visits\n${if(first==last)first else "$first – $last"}\n$itemCount work items",Modifier.testTag("dispatch-export-summary"))}
        items(visits,key={it.dispatchVisitId}){visit->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(10.dp)){Text("${visit.serviceDate}${visit.appointmentLocalTime?.let{" · $it"}.orEmpty()}");Text("${visit.managerReference?:visit.dispatchVisitId.take(8)} · ${visit.siteReference}");val current=currentGenerations[visit.dispatchVisitId];Text(when{current==null->"New → generation ${visit.generation}";visit.generation==current->"Unchanged → generation ${visit.generation}";else->"Updated → generation ${visit.generation}"})}}}
        item{error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button({val review=prepared;if(review==null){error=if(sender.isBlank())"Enter a sender label." else "Wait for the review to finish preparing."}else{busy=true;scope.launch{runCatching{withContext(Dispatchers.IO){svc.createExportFile(review,context.cacheDir)}}.onSuccess{artifact->shareExistingFile(context,artifact.file,WORK_PACKAGE_MIME,"Share ServiceLoop work package");nav.popBackStack()}.onFailure{failure->if(failure is CancellationException)throw failure else{error=if(failure.message?.contains("changed while") == true)"A selected Visit changed while review was open. The review has been refreshed; confirm it again." else failure.message;refresh++}};busy=false}}},Modifier.fillMaxWidth().testTag("dispatch-export-confirm"),enabled=!busy){Text("Create and share package")};Text("Back or Cancel before creation leaves status and generation unchanged.",style=MaterialTheme.typography.bodySmall)}
    }
}

@Composable internal fun CoordinatorHomeActions(nav:NavHostController){
    val context=LocalContext.current;val prefs=remember{context.getSharedPreferences(DISPATCH_PREFS,0)};var enabled by remember{mutableStateOf(prefs.getBoolean(COORDINATOR_ENABLED,false))}
    DisposableEffect(prefs){val listener=android.content.SharedPreferences.OnSharedPreferenceChangeListener{shared,key->if(key==COORDINATOR_ENABLED)enabled=shared.getBoolean(COORDINATOR_ENABLED,false)};prefs.registerOnSharedPreferenceChangeListener(listener);onDispose{prefs.unregisterOnSharedPreferenceChangeListener(listener)}}
    if(enabled)Row(Modifier.fillMaxWidth().testTag("coordinator-home-actions"),horizontalArrangement=Arrangement.spacedBy(6.dp)){OutlinedButton({nav.navigate("dispatch/technicians")},Modifier.weight(1f)){Text("Technicians",style=MaterialTheme.typography.labelMedium)};OutlinedButton({nav.navigate("dispatch/teams")},Modifier.weight(1f)){Text("Teams",style=MaterialTheme.typography.labelMedium)};Button({nav.navigate("dispatch/create")},Modifier.weight(1f)){Text("Outbox",style=MaterialTheme.typography.labelMedium)}}
}
