// Generated by tools/phosphor/phosphor_tool.py. Do not edit by hand.
package com.v16studio.serviceloop.ui.icons

import androidx.annotation.DrawableRes
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.material3.LocalContentColor
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.res.painterResource
import com.v16studio.serviceloop.R

object ServiceLoopIcons {
    @DrawableRes val Add = R.drawable.ic_sl_add
    @DrawableRes val Appearance = R.drawable.ic_sl_appearance
    @DrawableRes val ArrowCircleDown = R.drawable.ic_sl_arrow_circle_down
    @DrawableRes val ArrowCircleUp = R.drawable.ic_sl_arrow_circle_up
    @DrawableRes val ArrowDown = R.drawable.ic_sl_arrow_down
    @DrawableRes val ArrowFatLineDown = R.drawable.ic_sl_arrow_fat_line_down
    @DrawableRes val ArrowFatLineUp = R.drawable.ic_sl_arrow_fat_line_up
    @DrawableRes val ArrowUp = R.drawable.ic_sl_arrow_up
    @DrawableRes val Back = R.drawable.ic_sl_back
    @DrawableRes val Backup = R.drawable.ic_sl_backup
    @DrawableRes val Calendar = R.drawable.ic_sl_calendar
    @DrawableRes val Call = R.drawable.ic_sl_call
    @DrawableRes val Camera = R.drawable.ic_sl_camera
    @DrawableRes val CaretDown = R.drawable.ic_sl_caret_down
    @DrawableRes val CaretRight = R.drawable.ic_sl_caret_right
    @DrawableRes val Check = R.drawable.ic_sl_check
    @DrawableRes val CheckCircle = R.drawable.ic_sl_check_circle
    @DrawableRes val CheckFat = R.drawable.ic_sl_check_fat
    @DrawableRes val Circle = R.drawable.ic_sl_circle
    @DrawableRes val Copy = R.drawable.ic_sl_copy
    @DrawableRes val Customers = R.drawable.ic_sl_customers
    @DrawableRes val Delete = R.drawable.ic_sl_delete
    @DrawableRes val Disclosure = R.drawable.ic_sl_disclosure
    @DrawableRes val Dropdown = R.drawable.ic_sl_dropdown
    @DrawableRes val Equipment = R.drawable.ic_sl_equipment
    @DrawableRes val Error = R.drawable.ic_sl_error
    @DrawableRes val Expand = R.drawable.ic_sl_expand
    @DrawableRes val ExternalOpen = R.drawable.ic_sl_external_open
    @DrawableRes val EyeSlash = R.drawable.ic_sl_eye_slash
    @DrawableRes val History = R.drawable.ic_sl_history
    @DrawableRes val Home = R.drawable.ic_sl_home
    @DrawableRes val Info = R.drawable.ic_sl_info
    @DrawableRes val InspectionTemplates = R.drawable.ic_sl_inspection_templates
    @DrawableRes val LocalSaved = R.drawable.ic_sl_local_saved
    @DrawableRes val Lock = R.drawable.ic_sl_lock
    @DrawableRes val Mail = R.drawable.ic_sl_mail
    @DrawableRes val More = R.drawable.ic_sl_more
    @DrawableRes val PencilSimple = R.drawable.ic_sl_pencil_simple
    @DrawableRes val Person = R.drawable.ic_sl_person
    @DrawableRes val Photo = R.drawable.ic_sl_photo
    @DrawableRes val PlusBold = R.drawable.ic_sl_plus_bold
    @DrawableRes val Report = R.drawable.ic_sl_report
    @DrawableRes val Restore = R.drawable.ic_sl_restore
    @DrawableRes val Search = R.drawable.ic_sl_search
    @DrawableRes val SelectionCheck = R.drawable.ic_sl_selection_check
    @DrawableRes val SelectionChecked = R.drawable.ic_sl_selection_checked
    @DrawableRes val SelectionEmpty = R.drawable.ic_sl_selection_empty
    @DrawableRes val Settings = R.drawable.ic_sl_settings
    @DrawableRes val Share = R.drawable.ic_sl_share
    @DrawableRes val Site = R.drawable.ic_sl_site
    @DrawableRes val Sms = R.drawable.ic_sl_sms
    @DrawableRes val TeamRole = R.drawable.ic_sl_team_role
    @DrawableRes val Time = R.drawable.ic_sl_time
    @DrawableRes val Warning = R.drawable.ic_sl_warning
    @DrawableRes val WarningCircle = R.drawable.ic_sl_warning_circle
    @DrawableRes val Work = R.drawable.ic_sl_work
    @DrawableRes val X = R.drawable.ic_sl_x
    @DrawableRes val XCircle = R.drawable.ic_sl_x_circle
}

@Composable
fun serviceLoopIconPainter(@DrawableRes icon: Int): Painter = painterResource(icon)

@Composable
fun ServiceLoopIcon(
    @DrawableRes icon: Int,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    tint: Color = LocalContentColor.current,
) = Icon(serviceLoopIconPainter(icon), contentDescription, modifier, tint)
