// Generated by tools/phosphor/phosphor_tool.py. Do not edit by hand.
package com.v16studio.serviceloop.ui.icons

import androidx.annotation.DrawableRes
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.res.painterResource
import com.v16studio.serviceloop.R

object ServiceLoopIcons {
    @DrawableRes val Add = R.drawable.ic_sl_add
    @DrawableRes val Back = R.drawable.ic_sl_back
    @DrawableRes val Backup = R.drawable.ic_sl_backup
    @DrawableRes val Calendar = R.drawable.ic_sl_calendar
    @DrawableRes val Call = R.drawable.ic_sl_call
    @DrawableRes val Camera = R.drawable.ic_sl_camera
    @DrawableRes val Copy = R.drawable.ic_sl_copy
    @DrawableRes val Customers = R.drawable.ic_sl_customers
    @DrawableRes val Delete = R.drawable.ic_sl_delete
    @DrawableRes val Disclosure = R.drawable.ic_sl_disclosure
    @DrawableRes val Equipment = R.drawable.ic_sl_equipment
    @DrawableRes val Error = R.drawable.ic_sl_error
    @DrawableRes val Expand = R.drawable.ic_sl_expand
    @DrawableRes val ExternalOpen = R.drawable.ic_sl_external_open
    @DrawableRes val History = R.drawable.ic_sl_history
    @DrawableRes val Home = R.drawable.ic_sl_home
    @DrawableRes val Info = R.drawable.ic_sl_info
    @DrawableRes val LocalSaved = R.drawable.ic_sl_local_saved
    @DrawableRes val Lock = R.drawable.ic_sl_lock
    @DrawableRes val Mail = R.drawable.ic_sl_mail
    @DrawableRes val More = R.drawable.ic_sl_more
    @DrawableRes val Photo = R.drawable.ic_sl_photo
    @DrawableRes val Report = R.drawable.ic_sl_report
    @DrawableRes val Restore = R.drawable.ic_sl_restore
    @DrawableRes val Search = R.drawable.ic_sl_search
    @DrawableRes val Settings = R.drawable.ic_sl_settings
    @DrawableRes val Share = R.drawable.ic_sl_share
    @DrawableRes val Site = R.drawable.ic_sl_site
    @DrawableRes val Sms = R.drawable.ic_sl_sms
    @DrawableRes val Time = R.drawable.ic_sl_time
    @DrawableRes val Warning = R.drawable.ic_sl_warning
    @DrawableRes val Work = R.drawable.ic_sl_work
}

@Composable
fun serviceLoopIconPainter(@DrawableRes icon: Int): Painter = painterResource(icon)

@Composable
fun ServiceLoopIcon(
    @DrawableRes icon: Int,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    tint: Color = Color.Unspecified,
) = Icon(serviceLoopIconPainter(icon), contentDescription, modifier, tint)
