// Generated by tools/phosphor/phosphor_tool.py. Do not edit by hand.
package com.v16studio.serviceloop.ui.icons

import androidx.annotation.DrawableRes
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.res.painterResource
import com.v16studio.serviceloop.R

object ServiceLoopIcons {
    @DrawableRes val Add = R.drawable.ic_sl_add
    @DrawableRes val Back = R.drawable.ic_sl_back
    @DrawableRes val Customers = R.drawable.ic_sl_customers
    @DrawableRes val Disclosure = R.drawable.ic_sl_disclosure
    @DrawableRes val Error = R.drawable.ic_sl_error
    @DrawableRes val Expand = R.drawable.ic_sl_expand
    @DrawableRes val Home = R.drawable.ic_sl_home
    @DrawableRes val Info = R.drawable.ic_sl_info
    @DrawableRes val LocalSaved = R.drawable.ic_sl_local_saved
    @DrawableRes val More = R.drawable.ic_sl_more
    @DrawableRes val Search = R.drawable.ic_sl_search
    @DrawableRes val Settings = R.drawable.ic_sl_settings
    @DrawableRes val Time = R.drawable.ic_sl_time
    @DrawableRes val Warning = R.drawable.ic_sl_warning
    @DrawableRes val Work = R.drawable.ic_sl_work
}

@Composable
fun serviceLoopIconPainter(@DrawableRes icon: Int): Painter = painterResource(icon)

@Composable
fun ServiceLoopIcon(
    @DrawableRes icon: Int,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    tint: Color = Color.Unspecified,
) = Icon(serviceLoopIconPainter(icon), contentDescription, modifier, tint)
