package com.v16studio.serviceloop

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import com.v16studio.serviceloop.data.*
import com.v16studio.serviceloop.ui.reportShareEligible
import com.v16studio.serviceloop.ui.reportShareIntent
import java.time.Instant
import java.time.Clock
import java.time.ZoneId
import java.io.File
import com.v16studio.serviceloop.domain.ClockBusinessTime
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk=[35])
class DispatchPackageTest {
    private lateinit var db:ServiceLoopDatabase
    private lateinit var service:DispatchPackageService
    private lateinit var root:File
    @Before fun setup(){val context=ApplicationProvider.getApplicationContext<Context>();db=Room.inMemoryDatabaseBuilder(context,ServiceLoopDatabase::class.java).allowMainThreadQueries().build();root=File(context.cacheDir,"dispatch-test-${System.nanoTime()}").apply{mkdirs()};service=DispatchPackageService(db,root)}
    @After fun close(){db.close();root.deleteRecursively()}

    private suspend fun pkg(generation:Int=1,date:String="2026-09-12",assignedToSelf:Boolean=true,dispatchId:String="DV-1",itemId:String="ITEM-1"):DispatchPackage {
        val self=service.identity();val tech=DispatchTechnicianSnapshot(self.technicianId,self.name);val team=DispatchTeamSnapshot("TEAM-1","Field",listOf(self.technicianId),emptyList())
        return DispatchPackage("PKG-${generation}-${date}",Instant.parse("2026-09-08T10:00:00Z").toString(),"Central Service Team",listOf(DispatchCustomer("CU-D","Dispatch Customer")),listOf(DispatchSite("ST-D","CU-D","Dispatch Site","1 Test Road")),listOf(DispatchEquipment("EQ-D","ST-D","Pump","P-1","Maker","Model","S-1")),listOf(DispatchVisit(dispatchId,generation,"JOB-1",date,"09:30","Europe/Bucharest","ST-D","Ring office",listOf(team),listOf(tech),emptyList(),listOf(DispatchWork(itemId,"EQ-D","Annual service",assignedTechnicians=if(assignedToSelf)listOf(tech)else emptyList())))))
    }

    private suspend fun handoffFixture(dispatchId:String,itemId:String):Triple<String,String,DispatchTechnicianSnapshot>{val self=service.identity();val target=DispatchTechnicianSnapshot("target-$dispatchId-identity","Target");val snap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg(dispatchId=dispatchId,itemId=itemId);val visit=base.visits.single().copy(participants=listOf(snap,target),teams=listOf(DispatchTeamSnapshot("TEAM-$dispatchId","Both",listOf(snap.technicianId,target.technicianId),listOf(target.technicianId))),leaderTechnicianIds=listOf(target.technicianId));val local=service.import(service.preview(base.copy(packageId="P-$dispatchId",visits=listOf(visit)))).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(local)!!.copy(state="WORKING"));return Triple(local,db.serviceLoopDao().visitWorkItems(local).single().id,target)}
    private suspend fun attach(workId:String,id:String):File{val bytes="evidence-$id".toByteArray();val relative="attachments/$id/original";val file=File(root,relative).apply{parentFile?.mkdirs();writeBytes(bytes)};db.serviceLoopDao().insertAttachments(listOf(AttachmentEntity(id,"WORK_ITEM",workId,relative,sha256(bytes.toString(Charsets.UTF_8)),"$id.jpg","image/jpeg",false,"PRESENT",bytes.size.toLong())));return file}

    @Test fun identityIsStableAndRenameKeepsOpaqueId()=runTest{val first=service.identity();val second=service.identity();assertEquals(first,second);val renamed=service.renameIdentity("Maria");assertEquals(first.technicianId,renamed.technicianId);assertEquals("Maria",renamed.name);assertEquals(renamed,TechnicianIdentityCodec.decode(TechnicianIdentityCodec.encode(renamed)))}
    @Test fun technicianDirectoryRenameRequiresExplicitChoice()=runTest{val original=TechnicianIdentity("stable-technician-id","Old name");service.importTechnician(original);val incoming=original.copy(name="New name");val review=service.technicianRenameReview(incoming)!!;assertEquals("Old name",review.existingName);assertEquals("Old name",service.technicians().single().displayName);service.importTechnician(incoming,true);assertEquals("stable-technician-id",service.technicians().single().technicianId);assertEquals("New name",service.technicians().single().displayName)}
    @Test fun validV2RoundTripPreservesTimezoneAssignmentsAndReadableData()=runTest{val value=pkg();val decoded=DispatchPackageCodec.decode(DispatchPackageCodec.encode(value));assertEquals(value,decoded);assertEquals("Europe/Bucharest",decoded.visits.single().appointmentZoneId);assertEquals("Ring office",decoded.visits.single().instructions)}
    @Test fun rejectsV1MalformedDuplicateItemAndOutsideTeamAssignment()=runTest{val value=pkg();val json=DispatchPackageCodec.encode(value).toString(Charsets.UTF_8);assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.decode(json.replace("\"formatVersion\": 2","\"formatVersion\": 1").toByteArray())};assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.decode("not json".toByteArray())};assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.encode(value.copy(visits=listOf(value.visits.single().copy(work=value.visits.single().work+value.visits.single().work.single()))))};val outsider=DispatchTechnicianSnapshot("outsider-identity-0001","Outsider");assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.encode(value.copy(visits=listOf(value.visits.single().copy(work=listOf(value.visits.single().work.single().copy(assignedTechnicians=listOf(outsider)))))))} }
    @Test fun importUsesStableVisitAndItemIdentityAndDoesNotClaimRecurrence()=runTest{val value=pkg();val preview=service.preview(value);assertEquals(DispatchVisitClassification.NEW_VISIT,preview.visits.single().classification);val first=service.import(preview);val local=first.createdVisitIds.single();assertEquals("BOOKED",db.serviceLoopDao().visit(local)!!.state);assertEquals("Europe/Bucharest",db.serviceLoopDao().visit(local)!!.appointmentZoneId);assertEquals(1,db.serviceLoopDao().visitCount());assertTrue(db.serviceLoopDao().visitWorkItems(local).single().servicePlanId==null);assertEquals(DispatchVisitClassification.ALREADY_CURRENT,service.preview(value.copy(packageId="OTHER-TRANSPORT")).visits.single().classification);assertEquals(1,db.serviceLoopDao().visitCount());assertEquals("ITEM-1",db.dispatchDao().itemBindings("DV-1").single().dispatchItemId)}
    @Test fun newerGenerationUpdatesSameBookedVisitAndOlderDoesNotRollback()=runTest{val first=service.import(service.preview(pkg()));val local=first.createdVisitIds.single();val newer=pkg(2,"2026-09-14");val preview=service.preview(newer);assertEquals(DispatchVisitClassification.UPDATE,preview.visits.single().classification);assertEquals(listOf(local),service.import(preview).updatedVisitIds);assertEquals(1,db.serviceLoopDao().visitCount());assertEquals("2026-09-14",db.serviceLoopDao().visit(local)!!.actualServiceDate);assertEquals(DispatchVisitClassification.OLDER_GENERATION,service.preview(pkg(1,"2026-09-12")).visits.single().classification);assertEquals("2026-09-14",db.serviceLoopDao().visit(local)!!.actualServiceDate)}
    @Test fun sameGenerationDifferentMaterialConflictsAndLocalRescheduleBlocksNewer()=runTest{val local=service.import(service.preview(pkg())).createdVisitIds.single();assertEquals(DispatchVisitClassification.CONFLICT,service.preview(pkg(1,"2026-09-13")).visits.single().classification);val visit=db.serviceLoopDao().visit(local)!!;db.serviceLoopDao().updateVisit(visit.copy(actualServiceDate="2026-09-20"));assertEquals(DispatchVisitClassification.LOCAL_CONFLICT,service.preview(pkg(2,"2026-09-14")).visits.single().classification)}
    @Test fun startedVisitRejectsNewerGenerationWithoutDuplicate()=runTest{val local=service.import(service.preview(pkg())).createdVisitIds.single();val visit=db.serviceLoopDao().visit(local)!!;db.serviceLoopDao().updateVisit(visit.copy(state="WORKING"));assertEquals(DispatchVisitClassification.UPDATE_BLOCKED,service.preview(pkg(2,"2026-09-14")).visits.single().classification);assertEquals(1,db.serviceLoopDao().visitCount())}
    @Test fun emptyAssignmentMeansEveryoneAndNonParticipantGetsNothing()=runTest{val value=pkg(assignedToSelf=false);val p=service.preview(value);assertEquals("ASSIGNED",p.visits.single().items.single().localRole);assertEquals(DispatchVisitClassification.NEW_VISIT,p.visits.single().classification);val alex=DispatchTechnicianSnapshot("different-technician-01","Alex");val other=value.copy(visits=listOf(value.visits.single().copy(participants=listOf(alex),teams=listOf(DispatchTeamSnapshot("T2","Other",listOf(alex.technicianId),emptyList())),work=listOf(value.visits.single().work.single().copy(assignedTechnicians=listOf(alex))))));val notAssigned=service.preview(other);assertEquals(DispatchVisitClassification.NOT_ASSIGNED,notAssigned.visits.single().classification);assertFalse(notAssigned.canImport);assertEquals(0,db.serviceLoopDao().customerCount())}
    @Test fun teamsDeduplicateParticipantsAndSupportSeveralLeaders()=runTest{val a=TechnicianIdentity("tech-a-identity-0001","A");val b=TechnicianIdentity("tech-b-identity-0001","B");service.importTechnician(a);service.importTechnician(b);val t1=service.createTeam("North");val t2=service.createTeam("Emergency");service.setTeamMember(t1,a.technicianId,true,true);service.setTeamMember(t1,b.technicianId,true,true);service.setTeamMember(t2,a.technicianId,true,false);val teams=service.teams();assertEquals(2,teams.single{it.team.id==t1}.members.count{it.second});assertEquals(2,teams.flatMap{it.members}.map{it.first.technicianId}.toSet().size)}
    @Test fun officeShareKeepsVoidedAndSupersededSafety() {val uri=Uri.parse("content://serviceloop/report.pdf");val intent=reportShareIntent(uri,"office@example.com");assertEquals(Intent.ACTION_SEND,intent.action);assertArrayEquals(arrayOf("office@example.com"),intent.getStringArrayExtra(Intent.EXTRA_EMAIL));assertFalse(reportShareEligible(true,true,"ORIGINAL",false,false));assertTrue(reportShareEligible(true,true,"VOID_NOTICE",false,false))}

    @Test fun finalizationIncludesOnlyLocalDocumentationAndFreezesDispatchProvenance()=runTest{
        val dao=db.serviceLoopDao();dao.upsertBusinessProfile(BusinessProfileEntity(businessName="Service Co",technicianName="Report tech",phone=null,email=null,postalAddress=null,zoneId="Europe/Bucharest",modifiedAtEpochMillis=1));val value=pkg();val local=service.import(service.preview(value)).createdVisitIds.single();val repo=RoomServiceLoopRepository(db,ClockBusinessTime(Clock.fixed(Instant.parse("2026-09-12T08:00:00Z"),ZoneId.of("Europe/Bucharest")),ZoneId.of("Europe/Bucharest")));repo.startVisit(local);service.documentLocally(local,"ITEM-1");val work=dao.visitWorkItems(local).single();repo.savePublicWork(work.id,"Completed independently");repo.saveCompletionDraft(work.id,"PERFORMED",false,null,null,null,null);val record=(repo.finalizeVisit(local) as com.v16studio.serviceloop.domain.FinalizeResult.Success).recordId;val detail=repo.finalRecord(record)!!;assertEquals("DV-1",detail.public.dispatch!!.dispatchVisitId);assertEquals("ITEM-1",detail.public.lines.single().dispatchItemId);assertEquals(service.identity().technicianId,detail.public.dispatch!!.documentingTechnicianId)
    }

    @Test fun handoffIsNonExclusiveAndParticipationCompletionCreatesNoRecord()=runTest{
        val self=service.identity();val colleague=DispatchTechnicianSnapshot("colleague-identity-0001","Maria");val selfSnap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg();val visit=base.visits.single().copy(participants=listOf(selfSnap,colleague),teams=listOf(DispatchTeamSnapshot("TEAM-1","Field",listOf(self.technicianId,colleague.technicianId),listOf(colleague.technicianId))),leaderTechnicianIds=listOf(colleague.technicianId),work=listOf(base.visits.single().work.single().copy(assignedTechnicians=listOf(selfSnap))));val local=service.import(service.preview(base.copy(visits=listOf(visit)))).createdVisitIds.single();val current=db.serviceLoopDao().visit(local)!!;db.serviceLoopDao().updateVisit(current.copy(state="WORKING"));service.handoff(local,"ITEM-1",colleague);assertEquals("DEFERRED",db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.documentationDisposition);service.finishInvolvement(local);assertEquals("PARTICIPATION_COMPLETE",db.serviceLoopDao().visit(local)!!.state);assertNull(db.serviceLoopDao().finalRecordForVisit(local))
        assertEquals(listOf("DISPATCH_DOCUMENTATION_DEFERRED","DISPATCH_PARTICIPATION_COMPLETE"),db.serviceLoopDao().allChangeEntries().map{it.changeType})
    }

    @Test fun malformedTeamAndNameSnapshotsAreRejected()=runTest{
        val value=pkg();val visit=value.visits.single();val team=visit.teams.single();val self=visit.participants.single()
        fun rejected(v:DispatchVisit)=assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.encode(value.copy(visits=listOf(v)))}
        rejected(visit.copy(teams=listOf(team,team)))
        rejected(visit.copy(teams=listOf(team.copy(memberIds=team.memberIds+team.memberIds))))
        rejected(visit.copy(teams=listOf(team.copy(leaderIds=listOf("outsider-identity-01")))))
        rejected(visit.copy(work=listOf(visit.work.single().copy(assignedTechnicians=listOf(self.copy(name="Conflicting name"))))))
    }

    @Test fun recipientScopedDirectoryCreatesOnlyApplicableEquipment()=runTest{
        val self=service.identity();val john=DispatchTechnicianSnapshot(self.technicianId,self.name);val alex=DispatchTechnicianSnapshot("alex-identity-000001","Alex")
        val base=pkg();val visit=base.visits.single().copy(participants=listOf(john,alex),teams=listOf(DispatchTeamSnapshot("TEAM-1","Both",listOf(john.technicianId,alex.technicianId),emptyList())),work=listOf(DispatchWork("ITEM-A","EQ-A","Pump A",assignedTechnicians=listOf(john)),DispatchWork("ITEM-B","EQ-B","Pump B",assignedTechnicians=listOf(alex))))
        val value=base.copy(equipment=listOf(DispatchEquipment("EQ-A","ST-D","Pump A",null,null,null,"A"),DispatchEquipment("EQ-B","ST-D","Pump B",null,null,null,"B")),visits=listOf(visit));val preview=service.preview(value)
        assertTrue(preview.directory.any{it.reference=="EQ-A"});assertFalse(preview.directory.any{it.reference=="EQ-B"});service.import(preview);assertNotNull(db.serviceLoopDao().allEquipment().find{it.reference=="EQ-A"});assertNull(db.serviceLoopDao().allEquipment().find{it.reference=="EQ-B"})
    }

    @Test fun instructionsUpdateWithoutChangingTechnicianPrivateNote()=runTest{
        val first=pkg();val local=service.import(service.preview(first)).createdVisitIds.single();val work=db.serviceLoopDao().visitWorkItems(local).single();assertEquals("Ring office",db.dispatchDao().visitBinding("DV-1")!!.instructionsSnapshot);assertEquals("",db.serviceLoopDao().privateDraft(work.id)!!.internalNote)
        db.dispatchDao().updatePrivateDraftNote(work.id,"My private note");val second=first.copy(packageId="PKG-2",visits=listOf(first.visits.single().copy(generation=2,instructions="Use rear entrance")));service.import(service.preview(second));assertEquals("Use rear entrance",db.dispatchDao().visitBinding("DV-1")!!.instructionsSnapshot);assertEquals("My private note",db.serviceLoopDao().privateDraft(work.id)!!.internalNote)
    }

    @Test fun bookedAssignmentRemovalWithdrawsSameVisitAndStartedRemovalIsBlocked()=runTest{
        val first=pkg();val local=service.import(service.preview(first)).createdVisitIds.single();val other=DispatchTechnicianSnapshot("other-identity-0001","Other");val removed=first.copy(packageId="PKG-2",visits=listOf(first.visits.single().copy(generation=2,participants=listOf(other),teams=listOf(DispatchTeamSnapshot("TEAM-X","Other",listOf(other.technicianId),emptyList())),work=listOf(first.visits.single().work.single().copy(assignedTechnicians=listOf(other))))))
        assertEquals(DispatchVisitClassification.ASSIGNMENT_REMOVED,service.preview(removed).visits.single().classification);service.import(service.preview(removed));assertEquals("DISPATCH_WITHDRAWN",db.serviceLoopDao().visit(local)!!.state);assertEquals(1,db.serviceLoopDao().visitCount());assertEquals("DISPATCH_ASSIGNMENT_WITHDRAWN",db.serviceLoopDao().allChangeEntries().single().changeType)
        val second=pkg(dispatchId="DV-2",itemId="ITEM-2");val working=service.import(service.preview(second)).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(working)!!.copy(state="WORKING"));val removedWorking=removed.copy(packageId="PKG-X",visits=listOf(removed.visits.single().copy(dispatchVisitId="DV-2",work=listOf(removed.visits.single().work.single().copy(dispatchItemId="ITEM-2")))));assertEquals(DispatchVisitClassification.UPDATE_BLOCKED,service.preview(removedWorking).visits.single().classification);assertEquals(2,db.serviceLoopDao().visitCount())
    }

    @Test fun roleChangesPreserveWorkIdentityAndNeverClaim()=runTest{
        val first=pkg();val local=service.import(service.preview(first)).createdVisitIds.single();val workId=db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.localWorkItemId;val self=service.identity();val snap=DispatchTechnicianSnapshot(self.technicianId,self.name);val colleague=DispatchTechnicianSnapshot("leader-identity-0001","Leader")
        val everyone=first.copy(packageId="P2",visits=listOf(first.visits.single().copy(generation=2,work=listOf(first.visits.single().work.single().copy(assignedTechnicians=emptyList())))));service.import(service.preview(everyone));assertEquals("EVERYONE",db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.assignmentMeaning)
        val explicit=everyone.copy(packageId="P3",visits=listOf(everyone.visits.single().copy(generation=3,work=listOf(everyone.visits.single().work.single().copy(assignedTechnicians=listOf(snap))))));service.import(service.preview(explicit));assertEquals(workId,db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.localWorkItemId)
        val leaderOnly=explicit.copy(packageId="P4",visits=listOf(explicit.visits.single().copy(generation=4,participants=listOf(snap,colleague),teams=listOf(DispatchTeamSnapshot("T","Both",listOf(snap.technicianId,colleague.technicianId),listOf(snap.technicianId))),leaderTechnicianIds=listOf(snap.technicianId),work=listOf(explicit.visits.single().work.single().copy(assignedTechnicians=listOf(colleague))))));service.import(service.preview(leaderOnly));assertEquals("LEADER_VISIBLE",db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.localRole);assertNull(db.serviceLoopDao().visitWorkItems(local).single().capturedObligationId)
    }

    @Test fun handoffReleasesClaimUnlinksAndDoesNotAdvanceRecurrence()=runTest{
        val dao=db.serviceLoopDao();dao.insertCustomers(listOf(CustomerEntity("C","CU-D","Dispatch Customer")));dao.insertSites(listOf(SiteEntity("S","C","ST-D","Dispatch Site","1 Test Road",null)));dao.insertEquipment(listOf(EquipmentEntity("E","S","EQ-D","P-1","Pump","Maker","Model","S-1",null)));dao.insertPlans(listOf(ServicePlanEntity("P","E","PL-D","Annual",1,"YEARS","2026-09-12","ACTIVE","O")));dao.insertObligations(listOf(ServiceObligationEntity("O","P",1,"2026-09-12",1)))
        val self=service.identity();val colleague=DispatchTechnicianSnapshot("colleague-identity-0001","Maria");val selfSnap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg();val visit=base.visits.single().copy(participants=listOf(selfSnap,colleague),teams=listOf(DispatchTeamSnapshot("TEAM-1","Field",listOf(self.technicianId,colleague.technicianId),listOf(colleague.technicianId))),leaderTechnicianIds=listOf(colleague.technicianId),work=listOf(base.visits.single().work.single().copy(servicePlanReference="PL-D",dueDateSnapshot="2026-09-12",assignedTechnicians=listOf(selfSnap))));val local=service.import(service.preview(base.copy(visits=listOf(visit)))).createdVisitIds.single();dao.updateVisit(dao.visit(local)!!.copy(state="WORKING"));service.documentLocally(local,"ITEM-1");assertEquals(local,dao.claimForObligation("O"));service.handoff(local,"ITEM-1",colleague);val work=dao.visitWorkItems(local).single();assertNull(dao.claimForObligation("O"));assertNull(work.servicePlanId);assertNull(work.capturedObligationId);assertNull(dao.obligation("O")!!.consumedAtEpochMillis);assertEquals("2026-09-12",dao.plan("P")!!.currentDueDate);dao.insertVisits(listOf(dao.visit(local)!!.copy(id="OTHER-VISIT",reference="V-OTHER")));dao.insertVisitClaim(VisitClaimEntity("O","OTHER-VISIT",2));assertEquals("OTHER-VISIT",dao.claimForObligation("O"))
    }

    @Test fun destructiveHandoffRestoresFileAndDraftWhenTransactionFails()=runTest{
        val self=service.identity();val colleague=DispatchTechnicianSnapshot("colleague-identity-0001","Maria");val snap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg();val value=base.copy(visits=listOf(base.visits.single().copy(participants=listOf(snap,colleague),teams=listOf(DispatchTeamSnapshot("TEAM-1","Both",listOf(snap.technicianId,colleague.technicianId),listOf(colleague.technicianId))),leaderTechnicianIds=listOf(colleague.technicianId))));val local=service.import(service.preview(value)).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(local)!!.copy(state="WORKING"));val work=db.serviceLoopDao().visitWorkItems(local).single();val bytes="evidence".toByteArray();val relative="attachments/A/original";val file=File(root,relative).apply{parentFile?.mkdirs();writeBytes(bytes)};db.serviceLoopDao().insertAttachments(listOf(AttachmentEntity("A","WORK_ITEM",work.id,relative,sha256(bytes.toString(Charsets.UTF_8)),"a.jpg","image/jpeg",false,"PRESENT",bytes.size.toLong())))
        val failing=DispatchPackageService(db,root,DispatchMutationFault{if(it=="before_db_commit")throw IllegalStateException("injected DB failure")});assertThrows(IllegalStateException::class.java){kotlinx.coroutines.runBlocking{failing.handoff(local,"ITEM-1",colleague,true)}};assertTrue(file.isFile);assertNotNull(db.serviceLoopDao().attachment("A"));assertNotEquals("DEFERRED",db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.documentationDisposition)
    }

    @Test fun possibleDuplicateRequiresExplicitCreateOrSkipDecision()=runTest{
        db.serviceLoopDao().insertCustomers(listOf(CustomerEntity("existing","CU-X","Dispatch Customer")));val p=service.preview(pkg());assertFalse(p.canImport);val line=p.directory.single{it.classification==DispatchClassification.POSSIBLE_DUPLICATE};val create=service.resolveDuplicate(p,line.reference,DispatchDuplicateDecision.CREATE_SEPARATE);assertTrue(create.canImport);service.import(create);assertNotNull(db.serviceLoopDao().allCustomers().find{it.reference=="CU-D"})
    }
    @Test fun possibleDuplicateSkipOmitsDependentBranch()=runTest{db.serviceLoopDao().insertCustomers(listOf(CustomerEntity("existing","CU-X","Dispatch Customer")));val p=service.preview(pkg(dispatchId="DV-SKIP",itemId="ITEM-SKIP"));val line=p.directory.single{it.classification==DispatchClassification.POSSIBLE_DUPLICATE};val skip=service.resolveDuplicate(p,line.reference,DispatchDuplicateDecision.SKIP_BRANCH);assertTrue(skip.canImport);val result=service.import(skip);assertTrue(result.createdVisitIds.isEmpty());assertEquals(0,db.serviceLoopDao().visitCount());assertNull(db.serviceLoopDao().allCustomers().find{it.reference=="CU-D"})}

    @Test fun handoffPickerReturnsAllEligiblePeopleOnly()=runTest{val self=service.identity();val a=DispatchTechnicianSnapshot("eligible-a-identity","Alex");val leader=DispatchTechnicianSnapshot("eligible-b-identity","Blair");val unrelated=DispatchTechnicianSnapshot("unrelated-identity","Casey");val snap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg(dispatchId="DV-PICK",itemId="ITEM-PICK");val visit=base.visits.single().copy(participants=listOf(snap,a,leader,unrelated),teams=listOf(DispatchTeamSnapshot("T-PICK","Team",listOf(snap.technicianId,a.technicianId,leader.technicianId,unrelated.technicianId),listOf(leader.technicianId))),leaderTechnicianIds=listOf(leader.technicianId),work=listOf(base.visits.single().work.single().copy(assignedTechnicians=listOf(snap,a))));val local=service.import(service.preview(base.copy(packageId="P-PICK",visits=listOf(visit)))).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(local)!!.copy(state="WORKING"));assertEquals(setOf(a.technicianId,leader.technicianId),service.handoffReview(local,"ITEM-PICK").candidates.map{it.technicianId}.toSet())}

    @Test fun undoHandoffAppendsHistoryWithoutReclaiming()=runTest{val(local,_,target)=handoffFixture("DV-UNDO","ITEM-UNDO");service.handoff(local,"ITEM-UNDO",target);service.undoHandoff(local,"ITEM-UNDO");val binding=db.dispatchDao().itemBinding("DV-UNDO","ITEM-UNDO")!!;assertEquals("PENDING",binding.documentationDisposition);assertNull(binding.deferredToTechnicianId);assertEquals(0,db.serviceLoopDao().claimCountForVisit(local));assertEquals(listOf("DISPATCH_DOCUMENTATION_DEFERRED","DISPATCH_DOCUMENTATION_RESUMED"),db.serviceLoopDao().allChangeEntries().map{it.changeType})}

    @Test fun successfulDiscardRemovesExactEvidenceAndKeepsInstructions()=runTest{val(local,work,target)=handoffFixture("DV-SUCCESS","ITEM-SUCCESS");val file=attach(work,"SUCCESS");service.handoff(local,"ITEM-SUCCESS",target,true);assertFalse(file.exists());assertNull(db.serviceLoopDao().attachment("SUCCESS"));assertEquals("Ring office",db.dispatchDao().visitBinding("DV-SUCCESS")!!.instructionsSnapshot);assertEquals(target.technicianId,db.dispatchDao().itemBinding("DV-SUCCESS","ITEM-SUCCESS")!!.deferredToTechnicianId)}

    @Test fun fileFailureAndCancellationNeverCommitHandoff()=runTest{
        suspend fun verify(dispatchId:String,itemId:String,failure:Throwable){val(local,work,target)=handoffFixture(dispatchId,itemId);val file=attach(work,"A-$dispatchId");val failing=DispatchPackageService(db,root,DispatchMutationFault{if(it=="before_file_delete")throw failure});val thrown=runCatching{failing.handoff(local,itemId,target,true)}.exceptionOrNull();assertEquals(failure::class,thrown!!::class);assertEquals(failure.message,thrown.message);assertTrue(file.isFile);assertNotNull(db.serviceLoopDao().attachment("A-$dispatchId"));assertNotEquals("DEFERRED",db.dispatchDao().itemBinding(dispatchId,itemId)!!.documentationDisposition)}
        verify("DV-FILE","ITEM-FILE",IllegalStateException("file deletion failure"));verify("DV-CANCEL","ITEM-CANCEL",kotlinx.coroutines.CancellationException("cancelled"))
    }

    @Test fun completeBackupRestoresDispatchInstructionsTargetStateAndHistory()=runTest{ServiceLoopDatabase.configureStage4Tracking(db.openHelper.writableDatabase);val identity=service.identity();val(local,_,target)=handoffFixture("DV-BACKUP","ITEM-BACKUP");service.handoff(local,"ITEM-BACKUP",target);service.finishInvolvement(local);val password="dispatch backup passphrase".toCharArray();val recovery=RecoveryPackage(db,root);val backup=recovery.create(password,false);val inspection=recovery.inspect(backup.bytes,password);recovery.eraseDatabaseAndOwnedFiles("replacement-dataset");assertNull(db.dispatchDao().visitBinding("DV-BACKUP"));recovery.restore(inspection);assertEquals(identity.technicianId,service.identity().technicianId);assertEquals("Ring office",db.dispatchDao().visitBinding("DV-BACKUP")!!.instructionsSnapshot);assertEquals(target.technicianId,db.dispatchDao().itemBinding("DV-BACKUP","ITEM-BACKUP")!!.deferredToTechnicianId);assertEquals("PARTICIPATION_COMPLETE",db.serviceLoopDao().visit(local)!!.state);assertEquals(listOf("DISPATCH_DOCUMENTATION_DEFERRED","DISPATCH_PARTICIPATION_COMPLETE"),db.serviceLoopDao().allChangeEntries().map{it.changeType})}
}
