package com.v16studio.serviceloop

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import com.v16studio.serviceloop.data.*
import com.v16studio.serviceloop.ui.reportShareEligible
import com.v16studio.serviceloop.ui.reportShareIntent
import java.time.Instant
import java.time.Clock
import java.time.ZoneId
import java.io.File
import com.v16studio.serviceloop.domain.ClockBusinessTime
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.CancellationException
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk=[35])
class DispatchPackageTest {
    private lateinit var db:ServiceLoopDatabase
    private lateinit var service:DispatchPackageService
    private lateinit var root:File
    @Before fun setup(){val context=ApplicationProvider.getApplicationContext<Context>();db=Room.inMemoryDatabaseBuilder(context,ServiceLoopDatabase::class.java).allowMainThreadQueries().build();root=File(context.cacheDir,"dispatch-test-${System.nanoTime()}").apply{mkdirs()};service=DispatchPackageService(db,root)}
    @After fun close(){db.close();root.deleteRecursively()}

    private suspend fun pkg(generation:Int=1,date:String="2026-09-12",assignedToSelf:Boolean=true,dispatchId:String="DV-1",itemId:String="ITEM-1"):DispatchPackage {
        val self=service.identity();val tech=DispatchTechnicianSnapshot(self.technicianId,self.name);val team=DispatchTeamSnapshot("TEAM-1","Field",listOf(self.technicianId),emptyList())
        return DispatchPackage("PKG-${generation}-${date}",Instant.parse("2026-09-08T10:00:00Z").toString(),"Central Service Team",listOf(DispatchCustomer("CU-D","Dispatch Customer")),listOf(DispatchSite("ST-D","CU-D","Dispatch Site","1 Test Road")),listOf(DispatchEquipment("EQ-D","ST-D","Pump","P-1","Maker","Model","S-1")),listOf(DispatchVisit(dispatchId,generation,"JOB-1",date,"09:30","Europe/Bucharest","ST-D","Ring office",listOf(team),listOf(tech),emptyList(),listOf(DispatchWork(itemId,"EQ-D","Annual service",assignedTechnicians=if(assignedToSelf)listOf(tech)else emptyList())))))
    }

    private suspend fun handoffFixture(dispatchId:String,itemId:String):Triple<String,String,DispatchTechnicianSnapshot>{val self=service.identity();val target=DispatchTechnicianSnapshot("target-$dispatchId-identity","Target");val snap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg(dispatchId=dispatchId,itemId=itemId);val visit=base.visits.single().copy(participants=listOf(snap,target),teams=listOf(DispatchTeamSnapshot("TEAM-$dispatchId","Both",listOf(snap.technicianId,target.technicianId),listOf(target.technicianId))),leaderTechnicianIds=listOf(target.technicianId));val local=service.import(service.preview(base.copy(packageId="P-$dispatchId",visits=listOf(visit)))).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(local)!!.copy(state="WORKING"));return Triple(local,db.serviceLoopDao().visitWorkItems(local).single().id,target)}
    private suspend fun attach(workId:String,id:String):File{val bytes="evidence-$id".toByteArray();val relative="attachments/$id/original";val file=File(root,relative).apply{parentFile?.mkdirs();writeBytes(bytes)};db.serviceLoopDao().insertAttachments(listOf(AttachmentEntity(id,"WORK_ITEM",workId,relative,sha256(bytes.toString(Charsets.UTF_8)),"$id.jpg","image/jpeg",false,"PRESENT",bytes.size.toLong())));return file}
    private suspend fun coordinatorFixture():Pair<String,String>{val dao=db.serviceLoopDao();if(dao.customer("CO") == null){dao.insertCustomers(listOf(CustomerEntity("CO","CU-O","Office customer")));dao.insertSites(listOf(SiteEntity("SO","CO","ST-O","Office site",null,null)));dao.insertEquipment(listOf(EquipmentEntity("EO","SO","EQ-O",null,"Office pump",null,null,null,null)))};val self=service.identity();if(service.technicians().none{it.technicianId==self.technicianId})service.importTechnician(self);val team=service.teams().firstOrNull()?.team?.id?:service.createTeam("Office team").also{service.setTeamMember(it,self.technicianId,true)};return "SO" to team}
    private suspend fun outbox(reference:String,date:String="2026-09-14"):String{val(site,team)=coordinatorFixture();return service.createOutboxVisit(reference,site,date,"09:00","Europe/Bucharest",null,listOf(team)).also{service.addOutboxItem(it,"EO","Inspect $reference",null,null,emptyList())}}

    @Test fun identityIsStableAndRenameKeepsOpaqueId()=runTest{val first=service.identity();val second=service.identity();assertEquals(first,second);val renamed=service.renameIdentity("Maria");assertEquals(first.technicianId,renamed.technicianId);assertEquals("Maria",renamed.name);assertEquals(renamed,TechnicianIdentityCodec.decode(TechnicianIdentityCodec.encode(renamed)))}

    @Test fun backupInitializationUsesCanonicalIdentityAndCurrentSchemaMarker()=runTest{ServiceLoopDatabase.configureStage4Tracking(db.openHelper.writableDatabase);assertNull(db.dispatchDao().technicianIdentity());val recovery=RecoveryPackage(db,root);val password="canonical backup identity".toCharArray();recovery.inspect(recovery.create(password,false).bytes,password);val identity=db.dispatchDao().technicianIdentity()!!;assertTrue(TechnicianIdCodec.isValidCanonical(identity.technicianId));assertEquals(12,RecoveryPackage.SCHEMA_VERSION)}
    @Test fun backupRestoreRetainsPortableReminderPreferences()=runTest{ServiceLoopDatabase.configureStage4Tracking(db.openHelper.writableDatabase);val dao=db.serviceLoopDao();val custom=ReminderPreferencesEntity(summaryHour=9,summaryMinute=30,summaryDaysMask=21,dueSoonHorizonDays=30,appointmentAlertsEnabled=true,defaultAppointmentLeadMinutes=1440);dao.upsertReminderPreferences(custom);val recovery=RecoveryPackage(db,root);val password="portable reminder settings".toCharArray();val inspection=recovery.inspect(recovery.create(password,false).bytes,password);dao.upsertReminderPreferences(ReminderPreferencesEntity());recovery.restore(inspection);assertEquals(custom,dao.reminderPreferences())}
    @Test fun freshIdentityIsCanonicalAndManualEntryRejectsArbitraryText()=runTest{val identity=service.identity();assertEquals(identity.technicianId,TechnicianIdCodec.normalize(identity.technicianId));assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.importTechnicianManually(TechnicianIdentity("arbitrary-id","Invalid"))}};service.importTechnicianManually(TechnicianIdentity(identity.technicianId.lowercase().replace("-",""),"Canonical"));assertEquals(identity.technicianId,service.technicians().single().technicianId)}
    @Test fun existingLegacyPrimaryIdentityRemainsUnchanged()=runTest{db.dispatchDao().insertTechnicianIdentity(TechnicianIdentityEntity(technicianId="123e4567-e89b-42d3-a456-426614174000",displayName="Legacy",createdAtEpochMillis=1,modifiedAtEpochMillis=1));assertEquals("123e4567-e89b-42d3-a456-426614174000",service.identity().technicianId)}
    @Test fun technicianDirectoryRenameRequiresExplicitChoice()=runTest{val original=TechnicianIdentity("stable-technician-id","Old name");service.importTechnician(original);val incoming=original.copy(name="New name");val review=service.technicianRenameReview(incoming)!!;assertEquals("Old name",review.existingName);assertEquals("Old name",service.technicians().single().displayName);service.importTechnician(incoming,true);assertEquals("stable-technician-id",service.technicians().single().technicianId);assertEquals("New name",service.technicians().single().displayName)}
    @Test fun currentV3RoundTripPreservesTimezoneAssignmentsAndReadableData()=runTest{val value=pkg();val decoded=DispatchPackageCodec.decode(DispatchPackageCodec.encode(value));assertEquals(value,decoded);assertEquals("Europe/Bucharest",decoded.visits.single().appointmentZoneId);assertEquals("Ring office",decoded.visits.single().instructions)}
    @Test fun legacyV2PackagesRemainReadableAsActive()=runTest{val value=pkg();val legacy=DispatchPackageCodec.encode(value).toString(Charsets.UTF_8).replace("\"formatVersion\": 3","\"formatVersion\": 2").toByteArray();val decoded=DispatchPackageCodec.decode(legacy);assertEquals("ACTIVE",decoded.visits.single().transportLifecycle);assertNull(decoded.visits.single().cancellationReason)}
    @Test fun rejectsV1MalformedDuplicateItemAndOutsideTeamAssignment()=runTest{val value=pkg();val json=DispatchPackageCodec.encode(value).toString(Charsets.UTF_8);assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.decode(json.replace("\"formatVersion\": 3","\"formatVersion\": 1").toByteArray())};assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.decode("not json".toByteArray())};assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.encode(value.copy(visits=listOf(value.visits.single().copy(work=value.visits.single().work+value.visits.single().work.single()))))};val outsider=DispatchTechnicianSnapshot("outsider-identity-0001","Outsider");assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.encode(value.copy(visits=listOf(value.visits.single().copy(work=listOf(value.visits.single().work.single().copy(assignedTechnicians=listOf(outsider)))))))} }
    @Test fun importUsesStableVisitAndItemIdentityAndDoesNotClaimRecurrence()=runTest{val value=pkg();val preview=service.preview(value);assertEquals(DispatchVisitClassification.NEW_VISIT,preview.visits.single().classification);val first=service.import(preview);val local=first.createdVisitIds.single();assertEquals("BOOKED",db.serviceLoopDao().visit(local)!!.state);assertEquals("Europe/Bucharest",db.serviceLoopDao().visit(local)!!.appointmentZoneId);assertEquals(1,db.serviceLoopDao().visitCount());assertTrue(db.serviceLoopDao().visitWorkItems(local).single().servicePlanId==null);assertEquals(DispatchVisitClassification.ALREADY_CURRENT,service.preview(value.copy(packageId="OTHER-TRANSPORT")).visits.single().classification);assertEquals(1,db.serviceLoopDao().visitCount());assertEquals("ITEM-1",db.dispatchDao().itemBindings("DV-1").single().dispatchItemId)}
    @Test fun newerGenerationUpdatesSameBookedVisitAndOlderDoesNotRollback()=runTest{val first=service.import(service.preview(pkg()));val local=first.createdVisitIds.single();val newer=pkg(2,"2026-09-14");val preview=service.preview(newer);assertEquals(DispatchVisitClassification.UPDATE,preview.visits.single().classification);assertEquals(listOf(local),service.import(preview).updatedVisitIds);assertEquals(1,db.serviceLoopDao().visitCount());assertEquals("2026-09-14",db.serviceLoopDao().visit(local)!!.actualServiceDate);assertEquals(DispatchVisitClassification.OLDER_GENERATION,service.preview(pkg(1,"2026-09-12")).visits.single().classification);assertEquals("2026-09-14",db.serviceLoopDao().visit(local)!!.actualServiceDate)}
    @Test fun sameGenerationDifferentMaterialConflictsAndLocalRescheduleBlocksNewer()=runTest{val local=service.import(service.preview(pkg())).createdVisitIds.single();assertEquals(DispatchVisitClassification.CONFLICT,service.preview(pkg(1,"2026-09-13")).visits.single().classification);val visit=db.serviceLoopDao().visit(local)!!;db.serviceLoopDao().updateVisit(visit.copy(actualServiceDate="2026-09-20"));assertEquals(DispatchVisitClassification.LOCAL_CONFLICT,service.preview(pkg(2,"2026-09-14")).visits.single().classification)}
    @Test fun startedVisitRejectsNewerGenerationWithoutDuplicate()=runTest{val local=service.import(service.preview(pkg())).createdVisitIds.single();val visit=db.serviceLoopDao().visit(local)!!;db.serviceLoopDao().updateVisit(visit.copy(state="WORKING"));assertEquals(DispatchVisitClassification.UPDATE_BLOCKED,service.preview(pkg(2,"2026-09-14")).visits.single().classification);assertEquals(1,db.serviceLoopDao().visitCount())}
    @Test fun emptyAssignmentMeansEveryoneAndNonParticipantGetsNothing()=runTest{val value=pkg(assignedToSelf=false);val p=service.preview(value);assertEquals("ASSIGNED",p.visits.single().items.single().localRole);assertEquals(DispatchVisitClassification.NEW_VISIT,p.visits.single().classification);val alex=DispatchTechnicianSnapshot("different-technician-01","Alex");val other=value.copy(visits=listOf(value.visits.single().copy(participants=listOf(alex),teams=listOf(DispatchTeamSnapshot("T2","Other",listOf(alex.technicianId),emptyList())),work=listOf(value.visits.single().work.single().copy(assignedTechnicians=listOf(alex))))));val notAssigned=service.preview(other);assertEquals(DispatchVisitClassification.NOT_ASSIGNED,notAssigned.visits.single().classification);assertFalse(notAssigned.canImport);assertEquals(0,db.serviceLoopDao().customerCount())}
    @Test fun teamsDeduplicateParticipantsAndSupportSeveralLeaders()=runTest{val a=TechnicianIdentity("tech-a-identity-0001","A");val b=TechnicianIdentity("tech-b-identity-0001","B");service.importTechnician(a);service.importTechnician(b);val t1=service.createTeam("North");val t2=service.createTeam("Emergency");service.setTeamMember(t1,a.technicianId,true,true);service.setTeamMember(t1,b.technicianId,true,true);service.setTeamMember(t2,a.technicianId,true,false);val teams=service.teams();assertEquals(2,teams.single{it.team.id==t1}.members.count{it.second});assertEquals(2,teams.flatMap{it.members}.map{it.first.technicianId}.toSet().size)}
    @Test fun officeShareKeepsVoidedAndSupersededSafety() {val uri=Uri.parse("content://serviceloop/report.pdf");val intent=reportShareIntent(uri,"office@example.com");assertEquals(Intent.ACTION_SEND,intent.action);assertArrayEquals(arrayOf("office@example.com"),intent.getStringArrayExtra(Intent.EXTRA_EMAIL));assertFalse(reportShareEligible(true,true,"ORIGINAL",false,false));assertTrue(reportShareEligible(true,true,"VOID_NOTICE",false,false))}

    @Test fun finalizationIncludesOnlyLocalDocumentationAndFreezesDispatchProvenance()=runTest{
        val dao=db.serviceLoopDao();dao.upsertBusinessProfile(BusinessProfileEntity(businessName="Service Co",technicianName="Report tech",phone=null,email=null,postalAddress=null,zoneId="Europe/Bucharest",modifiedAtEpochMillis=1));val value=pkg();val local=service.import(service.preview(value)).createdVisitIds.single();val repo=RoomServiceLoopRepository(db,ClockBusinessTime(Clock.fixed(Instant.parse("2026-09-12T08:00:00Z"),ZoneId.of("Europe/Bucharest")),ZoneId.of("Europe/Bucharest")));repo.startVisit(local);service.documentLocally(local,"ITEM-1");val work=dao.visitWorkItems(local).single();repo.savePublicWork(work.id,"Completed independently");repo.saveCompletionDraft(work.id,"PERFORMED",false,null,null,null,null);val record=(repo.finalizeVisit(local) as com.v16studio.serviceloop.domain.FinalizeResult.Success).recordId;val detail=repo.finalRecord(record)!!;assertEquals("DV-1",detail.public.dispatch!!.dispatchVisitId);assertEquals("ITEM-1",detail.public.lines.single().dispatchItemId);assertEquals(service.identity().technicianId,detail.public.dispatch!!.documentingTechnicianId)
    }

    @Test fun handoffIsNonExclusiveAndParticipationCompletionCreatesNoRecord()=runTest{
        val self=service.identity();val colleague=DispatchTechnicianSnapshot("colleague-identity-0001","Maria");val selfSnap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg();val visit=base.visits.single().copy(participants=listOf(selfSnap,colleague),teams=listOf(DispatchTeamSnapshot("TEAM-1","Field",listOf(self.technicianId,colleague.technicianId),listOf(colleague.technicianId))),leaderTechnicianIds=listOf(colleague.technicianId),work=listOf(base.visits.single().work.single().copy(assignedTechnicians=listOf(selfSnap))));val local=service.import(service.preview(base.copy(visits=listOf(visit)))).createdVisitIds.single();val current=db.serviceLoopDao().visit(local)!!;db.serviceLoopDao().updateVisit(current.copy(state="WORKING"));service.handoff(local,"ITEM-1",colleague);assertEquals("DEFERRED",db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.documentationDisposition);service.finishInvolvement(local);assertEquals("COMPLETED",db.serviceLoopDao().visit(local)!!.state);assertNull(db.serviceLoopDao().finalRecordForVisit(local))
        assertEquals(setOf("DISPATCH_DOCUMENTATION_DEFERRED","DISPATCH_VISIT_COMPLETED"),db.serviceLoopDao().allChangeEntries().map{it.changeType}.toSet());assertEquals(2,db.serviceLoopDao().allChangeEntries().size)
    }

    @Test fun malformedTeamAndNameSnapshotsAreRejected()=runTest{
        val value=pkg();val visit=value.visits.single();val team=visit.teams.single();val self=visit.participants.single()
        fun rejected(v:DispatchVisit)=assertThrows(IllegalArgumentException::class.java){DispatchPackageCodec.encode(value.copy(visits=listOf(v)))}
        rejected(visit.copy(teams=listOf(team,team)))
        rejected(visit.copy(teams=listOf(team.copy(memberIds=team.memberIds+team.memberIds))))
        rejected(visit.copy(teams=listOf(team.copy(leaderIds=listOf("outsider-identity-01")))))
        rejected(visit.copy(work=listOf(visit.work.single().copy(assignedTechnicians=listOf(self.copy(name="Conflicting name"))))))
    }

    @Test fun recipientScopedDirectoryCreatesOnlyApplicableEquipment()=runTest{
        val self=service.identity();val john=DispatchTechnicianSnapshot(self.technicianId,self.name);val alex=DispatchTechnicianSnapshot("alex-identity-000001","Alex")
        val base=pkg();val visit=base.visits.single().copy(participants=listOf(john,alex),teams=listOf(DispatchTeamSnapshot("TEAM-1","Both",listOf(john.technicianId,alex.technicianId),emptyList())),work=listOf(DispatchWork("ITEM-A","EQ-A","Pump A",assignedTechnicians=listOf(john)),DispatchWork("ITEM-B","EQ-B","Pump B",assignedTechnicians=listOf(alex))))
        val value=base.copy(equipment=listOf(DispatchEquipment("EQ-A","ST-D","Pump A",null,null,null,"A"),DispatchEquipment("EQ-B","ST-D","Pump B",null,null,null,"B")),visits=listOf(visit));val preview=service.preview(value)
        assertTrue(preview.directory.any{it.reference=="EQ-A"});assertFalse(preview.directory.any{it.reference=="EQ-B"});service.import(preview);assertNotNull(db.serviceLoopDao().allEquipment().find{it.reference=="EQ-A"});assertNull(db.serviceLoopDao().allEquipment().find{it.reference=="EQ-B"})
    }

    @Test fun instructionsUpdateWithoutChangingTechnicianPrivateNote()=runTest{
        val first=pkg();val local=service.import(service.preview(first)).createdVisitIds.single();val work=db.serviceLoopDao().visitWorkItems(local).single();assertEquals("Ring office",db.dispatchDao().visitBinding("DV-1")!!.instructionsSnapshot);assertEquals("",db.serviceLoopDao().privateDraft(work.id)!!.internalNote)
        db.dispatchDao().updatePrivateDraftNote(work.id,"My private note");val second=first.copy(packageId="PKG-2",visits=listOf(first.visits.single().copy(generation=2,instructions="Use rear entrance")));service.import(service.preview(second));assertEquals("Use rear entrance",db.dispatchDao().visitBinding("DV-1")!!.instructionsSnapshot);assertEquals("My private note",db.serviceLoopDao().privateDraft(work.id)!!.internalNote)
    }

    @Test fun bookedAssignmentRemovalWithdrawsSameVisitAndStartedRemovalIsBlocked()=runTest{
        val first=pkg();val local=service.import(service.preview(first)).createdVisitIds.single();val other=DispatchTechnicianSnapshot("other-identity-0001","Other");val removed=first.copy(packageId="PKG-2",visits=listOf(first.visits.single().copy(generation=2,participants=listOf(other),teams=listOf(DispatchTeamSnapshot("TEAM-X","Other",listOf(other.technicianId),emptyList())),work=listOf(first.visits.single().work.single().copy(assignedTechnicians=listOf(other))))))
        assertEquals(DispatchVisitClassification.ASSIGNMENT_REMOVED,service.preview(removed).visits.single().classification);service.import(service.preview(removed));assertEquals("CANCELED",db.serviceLoopDao().visit(local)!!.state);assertEquals(1,db.serviceLoopDao().visitCount());assertEquals("DISPATCH_ASSIGNMENT_REMOVED",db.serviceLoopDao().allChangeEntries().single().changeType)
        val second=pkg(dispatchId="DV-2",itemId="ITEM-2");val working=service.import(service.preview(second)).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(working)!!.copy(state="WORKING"));val removedWorking=removed.copy(packageId="PKG-X",visits=listOf(removed.visits.single().copy(dispatchVisitId="DV-2",work=listOf(removed.visits.single().work.single().copy(dispatchItemId="ITEM-2")))));assertEquals(DispatchVisitClassification.ASSIGNMENT_REMOVED,service.preview(removedWorking).visits.single().classification);service.import(service.preview(removedWorking));assertEquals("CANCELED",db.serviceLoopDao().visit(working)!!.state);assertEquals(2,db.serviceLoopDao().visitCount())
    }

    @Test fun roleChangesPreserveWorkIdentityAndNeverClaim()=runTest{
        val first=pkg();val local=service.import(service.preview(first)).createdVisitIds.single();val workId=db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.localWorkItemId;val self=service.identity();val snap=DispatchTechnicianSnapshot(self.technicianId,self.name);val colleague=DispatchTechnicianSnapshot("leader-identity-0001","Leader")
        val everyone=first.copy(packageId="P2",visits=listOf(first.visits.single().copy(generation=2,work=listOf(first.visits.single().work.single().copy(assignedTechnicians=emptyList())))));service.import(service.preview(everyone));assertEquals("EVERYONE",db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.assignmentMeaning)
        val explicit=everyone.copy(packageId="P3",visits=listOf(everyone.visits.single().copy(generation=3,work=listOf(everyone.visits.single().work.single().copy(assignedTechnicians=listOf(snap))))));service.import(service.preview(explicit));assertEquals(workId,db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.localWorkItemId)
        val leaderOnly=explicit.copy(packageId="P4",visits=listOf(explicit.visits.single().copy(generation=4,participants=listOf(snap,colleague),teams=listOf(DispatchTeamSnapshot("T","Both",listOf(snap.technicianId,colleague.technicianId),listOf(snap.technicianId))),leaderTechnicianIds=listOf(snap.technicianId),work=listOf(explicit.visits.single().work.single().copy(assignedTechnicians=listOf(colleague))))));service.import(service.preview(leaderOnly));assertEquals("LEADER_VISIBLE",db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.localRole);assertNull(db.serviceLoopDao().visitWorkItems(local).single().capturedObligationId)
    }

    @Test fun handoffReleasesClaimUnlinksAndDoesNotAdvanceRecurrence()=runTest{
        val dao=db.serviceLoopDao();dao.insertCustomers(listOf(CustomerEntity("C","CU-D","Dispatch Customer")));dao.insertSites(listOf(SiteEntity("S","C","ST-D","Dispatch Site","1 Test Road",null)));dao.insertEquipment(listOf(EquipmentEntity("E","S","EQ-D","P-1","Pump","Maker","Model","S-1",null)));dao.insertPlans(listOf(ServicePlanEntity("P","E","PL-D","Annual",1,"YEARS","2026-09-12","ACTIVE","O")));dao.insertObligations(listOf(ServiceObligationEntity("O","P",1,"2026-09-12",1)))
        val self=service.identity();val colleague=DispatchTechnicianSnapshot("colleague-identity-0001","Maria");val selfSnap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg();val visit=base.visits.single().copy(participants=listOf(selfSnap,colleague),teams=listOf(DispatchTeamSnapshot("TEAM-1","Field",listOf(self.technicianId,colleague.technicianId),listOf(colleague.technicianId))),leaderTechnicianIds=listOf(colleague.technicianId),work=listOf(base.visits.single().work.single().copy(servicePlanReference="PL-D",dueDateSnapshot="2026-09-12",assignedTechnicians=listOf(selfSnap))));val local=service.import(service.preview(base.copy(visits=listOf(visit)))).createdVisitIds.single();dao.updateVisit(dao.visit(local)!!.copy(state="WORKING"));service.documentLocally(local,"ITEM-1");assertEquals(local,dao.claimForObligation("O"));service.handoff(local,"ITEM-1",colleague);val work=dao.visitWorkItems(local).single();assertNull(dao.claimForObligation("O"));assertNull(work.servicePlanId);assertNull(work.capturedObligationId);assertNull(dao.obligation("O")!!.consumedAtEpochMillis);assertEquals("2026-09-12",dao.plan("P")!!.currentDueDate);dao.insertVisits(listOf(dao.visit(local)!!.copy(id="OTHER-VISIT",reference="V-OTHER")));dao.insertVisitClaim(VisitClaimEntity("O","OTHER-VISIT",2));assertEquals("OTHER-VISIT",dao.claimForObligation("O"))
    }

    @Test fun destructiveHandoffRestoresFileAndDraftWhenTransactionFails()=runTest{
        val self=service.identity();val colleague=DispatchTechnicianSnapshot("colleague-identity-0001","Maria");val snap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg();val value=base.copy(visits=listOf(base.visits.single().copy(participants=listOf(snap,colleague),teams=listOf(DispatchTeamSnapshot("TEAM-1","Both",listOf(snap.technicianId,colleague.technicianId),listOf(colleague.technicianId))),leaderTechnicianIds=listOf(colleague.technicianId))));val local=service.import(service.preview(value)).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(local)!!.copy(state="WORKING"));val work=db.serviceLoopDao().visitWorkItems(local).single();val bytes="evidence".toByteArray();val relative="attachments/A/original";val file=File(root,relative).apply{parentFile?.mkdirs();writeBytes(bytes)};db.serviceLoopDao().insertAttachments(listOf(AttachmentEntity("A","WORK_ITEM",work.id,relative,sha256(bytes.toString(Charsets.UTF_8)),"a.jpg","image/jpeg",false,"PRESENT",bytes.size.toLong())))
        val failing=DispatchPackageService(db,root,DispatchMutationFault{if(it=="before_db_commit")throw IllegalStateException("injected DB failure")});assertThrows(IllegalStateException::class.java){kotlinx.coroutines.runBlocking{failing.handoff(local,"ITEM-1",colleague,true)}};assertTrue(file.isFile);assertNotNull(db.serviceLoopDao().attachment("A"));assertNotEquals("DEFERRED",db.dispatchDao().itemBinding("DV-1","ITEM-1")!!.documentationDisposition)
    }

    @Test fun possibleDuplicateRequiresExplicitCreateOrSkipDecision()=runTest{
        db.serviceLoopDao().insertCustomers(listOf(CustomerEntity("existing","CU-X","Dispatch Customer")));val p=service.preview(pkg());assertFalse(p.canImport);val line=p.directory.single{it.classification==DispatchClassification.POSSIBLE_DUPLICATE};val create=service.resolveDuplicate(p,line.reference,DispatchDuplicateDecision.CREATE_SEPARATE);assertTrue(create.canImport);service.import(create);assertNotNull(db.serviceLoopDao().allCustomers().find{it.reference=="CU-D"})
    }
    @Test fun possibleDuplicateSkipOmitsDependentBranch()=runTest{db.serviceLoopDao().insertCustomers(listOf(CustomerEntity("existing","CU-X","Dispatch Customer")));val p=service.preview(pkg(dispatchId="DV-SKIP",itemId="ITEM-SKIP"));val line=p.directory.single{it.classification==DispatchClassification.POSSIBLE_DUPLICATE};val skip=service.resolveDuplicate(p,line.reference,DispatchDuplicateDecision.SKIP_BRANCH);assertFalse(skip.canImport);assertTrue(skip.safeActionableVisits.isEmpty());assertEquals(0,db.serviceLoopDao().visitCount());assertNull(db.serviceLoopDao().allCustomers().find{it.reference=="CU-D"})}

    @Test fun batchExportUsesOneFileIndependentGenerationsAndTruthfulStatuses()=runTest{
        val a=outbox("A");val b=outbox("B");val c=outbox("C");val d=outbox("D");val e=outbox("E")
        service.createExportFile(listOf(c,d,e),"Office",root);service.rescheduleOutboxVisit(d,"2026-09-15","10:00","Europe/Bucharest");service.concludeOutboxVisits(listOf(e))
        val before=root.resolve("work-packages").listFiles{f->f.extension=="slwork"}.orEmpty().size
        val artifact=service.createExportFile(listOf(a,c,d),"Office",root);val decoded=DispatchPackageCodec.decode(artifact.file.readBytes());assertEquals(setOf(a,c,d),decoded.visits.map{it.dispatchVisitId}.toSet());assertFalse(decoded.visits.any{it.dispatchVisitId in setOf(b,e)});assertEquals(1,decoded.visits.single{it.dispatchVisitId==a}.generation);assertEquals(1,decoded.visits.single{it.dispatchVisitId==c}.generation);assertEquals(2,decoded.visits.single{it.dispatchVisitId==d}.generation);assertEquals(before+1,root.resolve("work-packages").listFiles{f->f.extension=="slwork"}.orEmpty().size);assertEquals(DispatchOutboxStatus.DISPATCHED,service.outboxVisits().single{it.dispatchVisitId==a}.outboxStatus);assertEquals(DispatchOutboxStatus.DRAFT,service.outboxVisits().single{it.dispatchVisitId==b}.outboxStatus);assertEquals(DispatchOutboxStatus.CONCLUDED,service.outboxVisits().single{it.dispatchVisitId==e}.outboxStatus)
    }

    @Test fun exportFailuresAndStalePreparationNeverAdvanceStatus()=runTest{
        suspend fun verify(checkpoint:String,failure:Throwable){val id=outbox(checkpoint);val failing=DispatchPackageService(db,root,DispatchMutationFault{if(it==checkpoint)throw failure});val thrown=runCatching{failing.createExportFile(listOf(id),"Office",root)}.exceptionOrNull();assertEquals(failure::class,thrown!!::class);val value=db.dispatchDao().outboxVisit(id)!!;assertEquals(DispatchOutboxStatus.DRAFT,value.outboxStatus);assertNull(value.lastExportedGeneration)}
        verify("before_export_file_write",IllegalStateException("write failed"));verify("after_export_file_write_before_commit",IllegalStateException("commit stopped"));verify("before_export_file_write",CancellationException("cancelled"))
        val stale=outbox("STALE");val prepared=service.prepareExport(listOf(stale),"Office");service.rescheduleOutboxVisit(stale,"2026-09-16","11:00","Europe/Bucharest");assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.commitPreparedExport(prepared)}};assertEquals(DispatchOutboxStatus.DRAFT,db.dispatchDao().outboxVisit(stale)!!.outboxStatus)
    }

    @Test fun concludeReopenAreAtomicAndNeverChangeGeneration()=runTest{
        val draft=outbox("DRAFT");assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.concludeOutboxVisits(listOf(draft))}}
        val ids=(1..10).map{outbox("STATUS-$it")};service.createExportFile(ids,"Office",root);val generations=ids.associateWith{db.dispatchDao().outboxVisit(it)!!.lastExportedGeneration};service.concludeOutboxVisits(ids);assertTrue(ids.all{db.dispatchDao().outboxVisit(it)!!.outboxStatus==DispatchOutboxStatus.CONCLUDED});assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.concludeOutboxVisits(listOf(ids.first(),draft))}};assertEquals(DispatchOutboxStatus.DRAFT,db.dispatchDao().outboxVisit(draft)!!.outboxStatus);service.reopenOutboxVisits(ids);assertTrue(ids.all{db.dispatchDao().outboxVisit(it)!!.outboxStatus==DispatchOutboxStatus.DISPATCHED});assertEquals(generations,ids.associateWith{db.dispatchDao().outboxVisit(it)!!.lastExportedGeneration});service.createExportFile(listOf(ids.first()),"Office",root);assertEquals(1,db.dispatchDao().outboxVisit(ids.first())!!.lastExportedGeneration);service.rescheduleOutboxVisit(ids.first(),"2026-09-20",null,"Europe/Bucharest");service.createExportFile(listOf(ids.first()),"Office",root);assertEquals(2,db.dispatchDao().outboxVisit(ids.first())!!.lastExportedGeneration)
    }

    @Test fun batchImportAppliesSafeVisitsWhileLocalConflictRemainsBlocked()=runTest{
        val first=pkg(dispatchId="V-CONFLICT",itemId="I-CONFLICT");val conflictedLocal=service.import(service.preview(first)).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(conflictedLocal)!!.copy(actualServiceDate="2026-10-01"))
        val fresh=pkg(dispatchId="V-SAFE",itemId="I-SAFE");val conflictUpdate=first.visits.single().copy(generation=2,serviceDate="2026-09-20");val batch=fresh.copy(packageId="BATCH",visits=listOf(fresh.visits.single(),conflictUpdate));val preview=service.preview(batch);assertEquals(1,preview.safeActionableVisits.size);assertEquals(DispatchVisitClassification.LOCAL_CONFLICT,preview.visits.single{it.dispatchVisitId=="V-CONFLICT"}.classification);val result=service.import(preview);assertEquals(1,result.createdVisitIds.size);assertTrue(result.updatedVisitIds.isEmpty());assertEquals(2,db.serviceLoopDao().visitCount());assertEquals("2026-10-01",db.serviceLoopDao().visit(conflictedLocal)!!.actualServiceDate)
    }

    @Test fun directoryConflictBlocksOnlyDependentVisitsAndSharedConflictBlocksBoth()=runTest{
        val self=service.identity();val tech=DispatchTechnicianSnapshot(self.technicianId,self.name);val team=DispatchTeamSnapshot("T","Team",listOf(self.technicianId),emptyList());val dao=db.serviceLoopDao();dao.insertCustomers(listOf(CustomerEntity("LC","CU-X","Customer X")));dao.insertSites(listOf(SiteEntity("LS","LC","ST-X","Site X",null,null)));dao.insertEquipment(listOf(EquipmentEntity("LE","LS","EQ-B",null,"Wrong equipment",null,null,"DIFFERENT",null)))
        fun visit(id:String,eq:String)=DispatchVisit(id,1,id,"2026-09-22",null,"Europe/Bucharest","ST-X",null,listOf(team),listOf(tech),emptyList(),listOf(DispatchWork("I-$id",eq,"Inspect",assignedTechnicians=listOf(tech))))
        val batch=DispatchPackage("DIR-BATCH",Instant.now().toString(),"Office",listOf(DispatchCustomer("CU-X","Customer X")),listOf(DispatchSite("ST-X","CU-X","Site X",null)),listOf(DispatchEquipment("EQ-A","ST-X","Safe equipment",null,null,null,"A"),DispatchEquipment("EQ-B","ST-X","Incoming equipment",null,null,null,"B")),listOf(visit("V-A","EQ-A"),visit("V-B","EQ-B")));val preview=service.preview(batch);assertEquals(listOf("V-A"),preview.safeActionableVisits.map{it.dispatchVisitId});service.import(preview);assertNotNull(db.dispatchDao().visitBinding("V-A"));assertNull(db.dispatchDao().visitBinding("V-B"));assertEquals("Wrong equipment",dao.equipment("LE")!!.name)
        dao.insertSites(listOf(SiteEntity("LS2","LC","ST-SHARED","Different local name",null,null)));val shared=batch.copy(packageId="SHARED",sites=listOf(DispatchSite("ST-SHARED","CU-X","Incoming shared site",null)),equipment=listOf(DispatchEquipment("EQ-C","ST-SHARED","C",null,null,null,null),DispatchEquipment("EQ-D","ST-SHARED","D",null,null,null,null)),visits=listOf(visit("V-C","EQ-C").copy(siteReference="ST-SHARED"),visit("V-D","EQ-D").copy(siteReference="ST-SHARED")));val sharedPreview=service.preview(shared);assertTrue(sharedPreview.safeActionableVisits.isEmpty());assertTrue(sharedPreview.visits.all{sharedPreview.directoryBlockers(it).any{x->x.reference=="ST-SHARED"}})
    }

    @Test fun backupRestorePreservesDraftDispatchedAndConcludedOutboxState()=runTest{ServiceLoopDatabase.configureStage4Tracking(db.openHelper.writableDatabase);val draft=outbox("REC-D");val dispatched=outbox("REC-X");val concluded=outbox("REC-C");service.createExportFile(listOf(dispatched,concluded),"Office",root);service.concludeOutboxVisits(listOf(concluded));val password="status recovery password".toCharArray();val recovery=RecoveryPackage(db,root);val inspection=recovery.inspect(recovery.create(password,false).bytes,password);recovery.eraseDatabaseAndOwnedFiles("replacement-status-dataset");recovery.restore(inspection);val restored=service.outboxVisits().associateBy{it.dispatchVisitId};assertEquals(DispatchOutboxStatus.DRAFT,restored.getValue(draft).outboxStatus);assertEquals(DispatchOutboxStatus.DISPATCHED,restored.getValue(dispatched).outboxStatus);assertEquals(DispatchOutboxStatus.CONCLUDED,restored.getValue(concluded).outboxStatus)}

    @Test fun backupInspectionRejectsMalformedDispatchRelationships()=runTest{ServiceLoopDatabase.configureStage4Tracking(db.openHelper.writableDatabase);val id=outbox("MALFORMED");val item=db.dispatchDao().outboxItems(id).single();val password="malformed dispatch backup".toCharArray();db.openHelper.writableDatabase.execSQL("PRAGMA foreign_keys=OFF");db.openHelper.writableDatabase.execSQL("UPDATE dispatch_outbox_items SET equipmentId='missing-equipment' WHERE dispatchItemId=?",arrayOf(item.dispatchItemId));val malformed=RecoveryPackage(db,root).create(password,false).bytes;db.openHelper.writableDatabase.execSQL("UPDATE dispatch_outbox_items SET equipmentId=? WHERE dispatchItemId=?",arrayOf(item.equipmentId,item.dispatchItemId));db.openHelper.writableDatabase.execSQL("PRAGMA foreign_keys=ON");assertTrue(runCatching{RecoveryPackage(db,root).inspect(malformed,password)}.isFailure);assertEquals(item.equipmentId,db.dispatchDao().outboxItems(id).single().equipmentId)}

    @Test fun concludedVisitRejectsDirectEditAndExportUntilReopened()=runTest{val id=outbox("CLOSED");service.createExportFile(listOf(id),"Office",root);service.concludeOutboxVisits(listOf(id));val value=db.dispatchDao().outboxVisit(id)!!;val team=service.outboxTeamIds(id);assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.prepareExport(listOf(id),"Office")}};assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.updateOutboxVisit(id,value.managerReference,value.siteId,value.serviceDate,value.appointmentLocalTime,value.appointmentZoneId,value.instructions,team)}};service.reopenOutboxVisits(listOf(id));assertEquals(DispatchOutboxStatus.DISPATCHED,db.dispatchDao().outboxVisit(id)!!.outboxStatus)}

    @Test fun handoffPickerReturnsAllEligiblePeopleOnly()=runTest{val self=service.identity();val a=DispatchTechnicianSnapshot("eligible-a-identity","Alex");val leader=DispatchTechnicianSnapshot("eligible-b-identity","Blair");val unrelated=DispatchTechnicianSnapshot("unrelated-identity","Casey");val snap=DispatchTechnicianSnapshot(self.technicianId,self.name);val base=pkg(dispatchId="DV-PICK",itemId="ITEM-PICK");val visit=base.visits.single().copy(participants=listOf(snap,a,leader,unrelated),teams=listOf(DispatchTeamSnapshot("T-PICK","Team",listOf(snap.technicianId,a.technicianId,leader.technicianId,unrelated.technicianId),listOf(leader.technicianId))),leaderTechnicianIds=listOf(leader.technicianId),work=listOf(base.visits.single().work.single().copy(assignedTechnicians=listOf(snap,a))));val local=service.import(service.preview(base.copy(packageId="P-PICK",visits=listOf(visit)))).createdVisitIds.single();db.serviceLoopDao().updateVisit(db.serviceLoopDao().visit(local)!!.copy(state="WORKING"));assertEquals(setOf(a.technicianId,leader.technicianId),service.handoffReview(local,"ITEM-PICK").candidates.map{it.technicianId}.toSet())}

    @Test fun undoHandoffAppendsHistoryWithoutReclaiming()=runTest{val(local,_,target)=handoffFixture("DV-UNDO","ITEM-UNDO");service.handoff(local,"ITEM-UNDO",target);service.undoHandoff(local,"ITEM-UNDO");val binding=db.dispatchDao().itemBinding("DV-UNDO","ITEM-UNDO")!!;assertEquals("PENDING",binding.documentationDisposition);assertNull(binding.deferredToTechnicianId);assertEquals(0,db.serviceLoopDao().claimCountForVisit(local));assertEquals(listOf("DISPATCH_DOCUMENTATION_DEFERRED","DISPATCH_DOCUMENTATION_RESUMED"),db.serviceLoopDao().allChangeEntries().map{it.changeType})}

    @Test fun successfulDiscardRemovesExactEvidenceAndKeepsInstructions()=runTest{val(local,work,target)=handoffFixture("DV-SUCCESS","ITEM-SUCCESS");val file=attach(work,"SUCCESS");service.handoff(local,"ITEM-SUCCESS",target,true);assertFalse(file.exists());assertNull(db.serviceLoopDao().attachment("SUCCESS"));assertEquals("Ring office",db.dispatchDao().visitBinding("DV-SUCCESS")!!.instructionsSnapshot);assertEquals(target.technicianId,db.dispatchDao().itemBinding("DV-SUCCESS","ITEM-SUCCESS")!!.deferredToTechnicianId)}

    @Test fun fileFailureAndCancellationNeverCommitHandoff()=runTest{
        suspend fun verify(dispatchId:String,itemId:String,failure:Throwable){val(local,work,target)=handoffFixture(dispatchId,itemId);val file=attach(work,"A-$dispatchId");val failing=DispatchPackageService(db,root,DispatchMutationFault{if(it=="before_file_delete")throw failure});val thrown=runCatching{failing.handoff(local,itemId,target,true)}.exceptionOrNull();assertEquals(failure::class,thrown!!::class);assertEquals(failure.message,thrown.message);assertTrue(file.isFile);assertNotNull(db.serviceLoopDao().attachment("A-$dispatchId"));assertNotEquals("DEFERRED",db.dispatchDao().itemBinding(dispatchId,itemId)!!.documentationDisposition)}
        verify("DV-FILE","ITEM-FILE",IllegalStateException("file deletion failure"));verify("DV-CANCEL","ITEM-CANCEL",kotlinx.coroutines.CancellationException("cancelled"))
    }

    @Test fun completeBackupRestoresDispatchInstructionsTargetStateAndHistory()=runTest{ServiceLoopDatabase.configureStage4Tracking(db.openHelper.writableDatabase);val identity=service.identity();val(local,_,target)=handoffFixture("DV-BACKUP","ITEM-BACKUP");service.handoff(local,"ITEM-BACKUP",target);service.finishInvolvement(local);val password="dispatch backup passphrase".toCharArray();val recovery=RecoveryPackage(db,root);val backup=recovery.create(password,false);val inspection=recovery.inspect(backup.bytes,password);recovery.eraseDatabaseAndOwnedFiles("replacement-dataset");assertNull(db.dispatchDao().visitBinding("DV-BACKUP"));recovery.restore(inspection);assertEquals(identity.technicianId,service.identity().technicianId);assertEquals("Ring office",db.dispatchDao().visitBinding("DV-BACKUP")!!.instructionsSnapshot);assertEquals(target.technicianId,db.dispatchDao().itemBinding("DV-BACKUP","ITEM-BACKUP")!!.deferredToTechnicianId);assertEquals("COMPLETED",db.serviceLoopDao().visit(local)!!.state);val restoredHistory=db.serviceLoopDao().allChangeEntries();assertEquals(setOf("DISPATCH_DOCUMENTATION_DEFERRED","DISPATCH_VISIT_COMPLETED"),restoredHistory.map{it.changeType}.toSet());assertEquals(2,restoredHistory.size)}

    @Test fun coordinatorCancellationRequiresReasonAndCanceledDraftCannotExport()=runTest{val visit=outbox("JOB-CANCEL-DRAFT");assertEquals(DispatchOutboxStatus.DRAFT,db.dispatchDao().outboxVisit(visit)!!.outboxStatus);assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.cancelOutboxVisits(listOf(visit)," ")}};service.cancelOutboxVisits(listOf(visit),"Customer canceled");val canceled=db.dispatchDao().outboxVisit(visit)!!;assertEquals(DispatchOutboxStatus.CANCELED,canceled.outboxStatus);assertEquals("Customer canceled",canceled.cancellationReason);assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.prepareExport(listOf(visit),"Coordinator")}}}
    @Test fun canceledDispatchedVisitUsesOneNewGenerationAndRetryIsStable()=runTest{val visit=outbox("JOB-CANCEL-SENT");val first=service.prepareExport(listOf(visit),"Coordinator");service.commitPreparedExport(first);assertEquals(1,db.dispatchDao().outboxVisit(visit)!!.lastExportedGeneration);service.cancelOutboxVisits(listOf(visit),"Access withdrawn");val canceled=service.prepareExport(listOf(visit),"Coordinator");assertEquals(2,canceled.packageValue.visits.single().generation);assertEquals("CANCELED",canceled.packageValue.visits.single().transportLifecycle);assertEquals("Access withdrawn",canceled.packageValue.visits.single().cancellationReason);service.commitPreparedExport(canceled);val retry=service.prepareExport(listOf(visit),"Coordinator");assertEquals(2,retry.packageValue.visits.single().generation);assertEquals(canceled.packageValue.visits.single().cancellationReason,retry.packageValue.visits.single().cancellationReason)}

    @Test fun coherentEditorSaveCreatesAndUpdatesOneDefinitionWithStableIds()=runTest{
        val(site,team)=coordinatorFixture();val itemId="stable-editor-item"
        val visitId=service.saveOutboxVisit(DispatchOutboxEditorDraft(managerReference="JOB-EDITOR",siteId=site,serviceDate="2026-09-25",appointmentLocalTime="10:30",appointmentZoneId="Europe/Bucharest",instructions="Gate code",teamIds=listOf(team),items=listOf(DispatchOutboxItemDraft(itemId,"EO","Inspect pump",assignedTechnicianIds=emptyList()))))
        val created=db.dispatchDao().outboxVisit(visitId)!!;assertEquals(DispatchOutboxStatus.DRAFT,created.outboxStatus);assertEquals(listOf(team),service.outboxTeamIds(visitId));assertEquals(itemId,service.outboxItems(visitId).single().first.dispatchItemId)
        val updatedId=service.saveOutboxVisit(DispatchOutboxEditorDraft(visitId,created.modifiedAtEpochMillis,"JOB-EDITOR-2",site,"2026-09-26",null,"Europe/Bucharest","Rear gate",listOf(team),listOf(DispatchOutboxItemDraft(itemId,"EO","Inspect and test",assignedTechnicianIds=emptyList()))))
        assertEquals(visitId,updatedId);assertEquals(itemId,service.outboxItems(visitId).single().first.dispatchItemId);assertEquals("Inspect and test",service.outboxItems(visitId).single().first.taskName);assertNull(db.dispatchDao().outboxVisit(visitId)!!.lastExportedGeneration)
    }

    @Test fun coherentEditorSaveRejectsStaleConcludedAndInvalidDefinitionsAtomically()=runTest{
        val(site,team)=coordinatorFixture();val id=outbox("EDITOR-GUARD");val original=db.dispatchDao().outboxVisit(id)!!;val originalItem=service.outboxItems(id).single().first
        service.rescheduleOutboxVisit(id,"2026-09-30",null,"Europe/Bucharest")
        val stale=DispatchOutboxEditorDraft(id,original.modifiedAtEpochMillis,"STALE",site,"2026-09-29",null,"Europe/Bucharest",null,listOf(team),listOf(DispatchOutboxItemDraft(originalItem.dispatchItemId,"EO","Stale change")))
        assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.saveOutboxVisit(stale)}};assertEquals("EDITOR-GUARD",db.dispatchDao().outboxVisit(id)!!.managerReference);assertEquals("Inspect EDITOR-GUARD",service.outboxItems(id).single().first.taskName)
        service.createExportFile(listOf(id),"Office",root);service.concludeOutboxVisits(listOf(id));val concluded=db.dispatchDao().outboxVisit(id)!!;assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.saveOutboxVisit(stale.copy(expectedModifiedAtEpochMillis=concluded.modifiedAtEpochMillis))}};assertEquals(DispatchOutboxStatus.CONCLUDED,db.dispatchDao().outboxVisit(id)!!.outboxStatus)
        val legacyId=outbox("LEGACY-EDITOR-GUARD");val beforeLegacyItemChange=db.dispatchDao().outboxVisit(legacyId)!!;val firstLegacyItem=service.outboxItems(legacyId).single().first;service.addOutboxItem(legacyId,"EO","Second task",null,null,emptyList());val editorBeforeLegacyItemChange=DispatchOutboxEditorDraft(legacyId,beforeLegacyItemChange.modifiedAtEpochMillis,"OVERWRITE",site,beforeLegacyItemChange.serviceDate,beforeLegacyItemChange.appointmentLocalTime,beforeLegacyItemChange.appointmentZoneId,null,listOf(team),listOf(DispatchOutboxItemDraft(firstLegacyItem.dispatchItemId,"EO","Overwrite")));assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.saveOutboxVisit(editorBeforeLegacyItemChange)}};assertEquals(2,service.outboxItems(legacyId).size)
    }

    @Test fun reviewedPreparationIsTheArtifactAndStaleReviewLeavesNoFileOrStatus()=runTest{
        val id=outbox("REVIEWED");val prepared=service.prepareExport(listOf(id),"Coordinator");assertEquals(DispatchOutboxStatus.DRAFT,db.dispatchDao().outboxVisit(id)!!.outboxStatus)
        val artifact=service.createExportFile(prepared,root);assertEquals(prepared.packageValue.packageId,artifact.packageValue.packageId);assertArrayEquals(prepared.bytes,artifact.file.readBytes());assertEquals(DispatchOutboxStatus.DISPATCHED,db.dispatchDao().outboxVisit(id)!!.outboxStatus)
        val staleId=outbox("STALE-REVIEW");val stale=service.prepareExport(listOf(staleId),"Coordinator");service.rescheduleOutboxVisit(staleId,"2026-10-02",null,"Europe/Bucharest");assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.createExportFile(stale,root)}};assertEquals(DispatchOutboxStatus.DRAFT,db.dispatchDao().outboxVisit(staleId)!!.outboxStatus);assertFalse(root.resolve("work-packages").listFiles().orEmpty().any{it.name.contains(stale.packageValue.packageId.take(8))})
        val directoryStaleId=outbox("DIRECTORY-STALE");val directoryStale=service.prepareExport(listOf(directoryStaleId),"Coordinator");val customer=db.serviceLoopDao().customer("CO")!!;db.serviceLoopDao().updateCustomer(customer.copy(name="Renamed after review"));assertThrows(IllegalArgumentException::class.java){kotlinx.coroutines.runBlocking{service.createExportFile(directoryStale,root)}};assertEquals(DispatchOutboxStatus.DRAFT,db.dispatchDao().outboxVisit(directoryStaleId)!!.outboxStatus);assertFalse(root.resolve("work-packages").listFiles().orEmpty().any{it.name.contains(directoryStale.packageValue.packageId.take(8))})
    }}
